# 04 — Tableau Data Export and Dashboard Preparation

## Purpose

This notebook prepares validated analytical outputs from the preceding dissertation notebooks for visual communication in Tableau.

No models are trained, tuned or modified in this notebook. No new model-selection decisions are made. Instead, previously established dataset, predictive-performance and explainability results are reorganised into compact Tableau-ready datasets.

The planned Tableau visualisation is organised around three analytical themes:

1. **Dataset and Churn Profile** — communicates the characteristics of the telecommunications dataset, including class imbalance and relevant customer characteristics.
2. **Comparative Model Performance** — compares the five frozen imbalance-aware classifiers using held-out predictive metrics and confusion-matrix results.
3. **Explainability and Final Model Selection** — communicates cross-model feature importance, perturbation sensitivity and the evidence supporting the final selection of LightGBM.

The dashboards are intended as a visual communication layer over the validated dissertation analysis rather than an additional modelling or optimisation stage.

In [ ]:
# ============================================================
# Cell 1 — Setup and Authoritative Artefact Discovery
# ============================================================

from google.colab import drive

import os
import sys
import platform
import pandas as pd
import numpy as np


print("=== Notebook 4: Tableau Export Preparation ===\n")


# ------------------------------------------------------------
# Mount Google Drive
# ------------------------------------------------------------

drive.mount(
    "/content/drive"
)


# ------------------------------------------------------------
# Authoritative dissertation paths
# ------------------------------------------------------------

PROJECT = (
    "/content/drive/MyDrive/"
    "7005SCN_Dissertation"
)

DATA = os.path.join(
    PROJECT,
    "dataset"
)

OUTPUTS = os.path.join(
    PROJECT,
    "outputs"
)

MODELS = os.path.join(
    PROJECT,
    "models"
)

TABLEAU = os.path.join(
    PROJECT,
    "tableau"
)


# Tableau-specific export directory
os.makedirs(
    TABLEAU,
    exist_ok=True
)


# ------------------------------------------------------------
# Environment information
# ------------------------------------------------------------

print("\n=== Environment ===")

print(
    "Python:",
    sys.version.split()[0]
)

print(
    "Platform:",
    platform.platform()
)

print(
    "pandas:",
    pd.__version__
)

print(
    "NumPy:",
    np.__version__
)


# ------------------------------------------------------------
# Confirm dissertation directories
# ------------------------------------------------------------

print("\n=== Dissertation Directories ===")

directories = {
    "Project": PROJECT,
    "Dataset": DATA,
    "Outputs": OUTPUTS,
    "Models": MODELS,
    "Tableau": TABLEAU
}


for name, path in directories.items():

    print(
        f"{name:<10}: "
        f"{path} "
        f"[exists={os.path.exists(path)}]"
    )


assert os.path.exists(PROJECT)
assert os.path.exists(DATA)
assert os.path.exists(OUTPUTS)
assert os.path.exists(MODELS)
assert os.path.exists(TABLEAU)


# ------------------------------------------------------------
# Inventory existing analytical outputs
# ------------------------------------------------------------

output_files = sorted([
    filename
    for filename in os.listdir(OUTPUTS)
    if os.path.isfile(
        os.path.join(
            OUTPUTS,
            filename
        )
    )
])


print(
    "\n=== Existing Analytical Outputs ==="
)

print(
    "Files discovered:",
    len(output_files)
)


for filename in output_files:

    filepath = os.path.join(
        OUTPUTS,
        filename
    )

    size_bytes = os.path.getsize(
        filepath
    )

    print(
        f"{filename:<60} "
        f"{size_bytes:>10,} bytes"
    )


# ------------------------------------------------------------
# Identify Tableau-relevant artefacts already produced
# ------------------------------------------------------------

tableau_relevant_names = [

    "cross_model_explainability_ranks.csv",

    "cross_model_spearman_rank_correlation.csv",

    "cross_model_explainability_summary.csv",

    "cross_model_perturbation_sensitivity.csv",

    "cross_model_top_perturbation_feature.csv",

    "final_performance_interpretability_assessment.csv",

    "qualitative_performance_interpretability_tradeoff.csv",

    "final_model_selection_evidence.csv",

    "decision_tree_intrinsic_feature_importance.csv",

    "feature_names_explainability.json"
]


artefact_rows = []


for filename in tableau_relevant_names:

    filepath = os.path.join(
        OUTPUTS,
        filename
    )

    exists = os.path.exists(
        filepath
    )

    artefact_rows.append({

        "Artefact":
            filename,

        "Exists":
            exists,

        "Size (bytes)":
            (
                os.path.getsize(filepath)
                if exists
                else 0
            )
    })


tableau_source_audit_df = pd.DataFrame(
    artefact_rows
)


print(
    "\n=== Known Tableau-Relevant Artefacts ===\n"
)

display(
    tableau_source_audit_df
)


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

notebook3_sources_present = (
    tableau_source_audit_df[
        "Exists"
    ].all()
)


print(
    "\nKnown Notebook 3 artefacts available:",
    f"{int(tableau_source_audit_df['Exists'].sum())}"
    f"/{len(tableau_source_audit_df)}"
)


assert notebook3_sources_present


print(
    "\nTableau export directory:"
)

print(
    TABLEAU
)


print(
    "\nNOTEBOOK_4_SETUP_VALID: True"
)

=== Notebook 4: Tableau Export Preparation ===

Mounted at /content/drive

=== Environment ===
Python: 3.13.15
Platform: Linux-6.6.122+-x86_64-with-glibc2.39
pandas: 2.2.3
NumPy: 2.1.3

=== Dissertation Directories ===
Project   : /content/drive/MyDrive/7005SCN_Dissertation [exists=True]
Dataset   : /content/drive/MyDrive/7005SCN_Dissertation/dataset [exists=True]
Outputs   : /content/drive/MyDrive/7005SCN_Dissertation/outputs [exists=True]
Models    : /content/drive/MyDrive/7005SCN_Dissertation/models [exists=True]
Tableau   : /content/drive/MyDrive/7005SCN_Dissertation/tableau [exists=True]

=== Existing Analytical Outputs ===
Files discovered: 27
cross_model_explainability_ranks.csv                              1,228 bytes
cross_model_explainability_summary.csv                              701 bytes
cross_model_perturbation_sensitivity.csv                          3,334 bytes
cross_model_spearman_rank_correlation.csv                           329 bytes
cross_model_top_perturbation_feature.csv                            570 bytes
decision_tree_complete_rules.txt                                 20,033 bytes
decision_tree_intrinsic_feature_importance.csv                      942 bytes
feature_name_mapping.json                                           856 bytes
feature_names_explainability.json                                   790 bytes
final_model_selection_evidence.csv                                1,408 bytes
final_performance_interpretability_assessment.csv                 1,057 bytes
imbalance_aware_effect_comparison.csv                             1,279 bytes
imbalance_aware_model_ranking.csv                                   720 bytes
lightgbm_shap_beeswarm.png                                      411,650 bytes
lightgbm_shap_global_bar.png                                    308,495 bytes
lightgbm_shap_local_waterfall.png                               302,869 bytes
lr_coefficient_plot.png                                         358,103 bytes
model_comparison_frozen_results.csv                               1,566 bytes
qualitative_performance_interpretability_tradeoff.csv             1,673 bytes
random_forest_shap_beeswarm.png                                 387,016 bytes
random_forest_shap_global_bar.png                               301,752 bytes
random_forest_shap_importance.csv                                 1,008 bytes
random_forest_shap_values.npz                                    15,570 bytes
xgboost_shap_beeswarm.png                                       385,153 bytes
xgboost_shap_global_bar.png                                     316,238 bytes
xgboost_shap_importance.csv                                         841 bytes
xgboost_shap_values.npz                                          63,112 bytes

=== Known Tableau-Relevant Artefacts ===

                                            Artefact  Exists  Size (bytes)
0               cross_model_explainability_ranks.csv    True          1228
1          cross_model_spearman_rank_correlation.csv    True           329
2             cross_model_explainability_summary.csv    True           701
3           cross_model_perturbation_sensitivity.csv    True          3334
4           cross_model_top_perturbation_feature.csv    True           570
5  final_performance_interpretability_assessment.csv    True          1057
6  qualitative_performance_interpretability_trade...    True          1673
7                 final_model_selection_evidence.csv    True          1408
8     decision_tree_intrinsic_feature_importance.csv    True           942
9                  feature_names_explainability.json    True           790

Known Notebook 3 artefacts available: 10/10

Tableau export directory:
/content/drive/MyDrive/7005SCN_Dissertation/tableau

NOTEBOOK_4_SETUP_VALID: True

In [ ]:
# ============================================================
# Cell 2 — Inspect Authoritative Tableau Source Datasets
# ============================================================

import os
import pandas as pd


print("=== Tableau Source Dataset Inspection ===\n")


# ------------------------------------------------------------
# Authoritative CSV artefacts likely to feed Tableau
# ------------------------------------------------------------

source_files = [

    # Notebook 2 — predictive performance
    "model_comparison_frozen_results.csv",
    "imbalance_aware_model_ranking.csv",
    "imbalance_aware_effect_comparison.csv",

    # Notebook 3 — explainability
    "cross_model_explainability_ranks.csv",
    "cross_model_perturbation_sensitivity.csv",
    "cross_model_top_perturbation_feature.csv",
    "cross_model_explainability_summary.csv",

    # Notebook 3 — final assessment
    "final_performance_interpretability_assessment.csv",
    "qualitative_performance_interpretability_tradeoff.csv",
    "final_model_selection_evidence.csv"
]


source_datasets = {}


# ------------------------------------------------------------
# Load and inspect each source
# ------------------------------------------------------------

for filename in source_files:

    filepath = os.path.join(
        OUTPUTS,
        filename
    )

    assert os.path.exists(
        filepath
    ), f"Missing required source: {filename}"

    df = pd.read_csv(
        filepath
    )

    source_datasets[
        filename
    ] = df

    print(
        "=" * 80
    )

    print(
        f"SOURCE: {filename}"
    )

    print(
        f"Shape: {df.shape}"
    )

    print(
        "Columns:"
    )

    print(
        list(df.columns)
    )

    print(
        "\nContents:"
    )

    display(
        df
    )

    print()


# ------------------------------------------------------------
# Compact source inventory
# ------------------------------------------------------------

source_inventory_rows = []


for filename, df in source_datasets.items():

    source_inventory_rows.append({

        "Source File":
            filename,

        "Rows":
            len(df),

        "Columns":
            len(df.columns),

        "Duplicate Rows":
            int(
                df.duplicated().sum()
            ),

        "Missing Cells":
            int(
                df.isna().sum().sum()
            )
    })


tableau_source_inventory_df = pd.DataFrame(
    source_inventory_rows
)


print(
    "=" * 80
)

print(
    "\n=== Source Inventory Summary ===\n"
)


display(
    tableau_source_inventory_df
)


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert len(
    source_datasets
) == len(
    source_files
)

assert all(
    len(df) > 0
    for df in source_datasets.values()
)


print(
    "\nSources successfully loaded:",
    len(source_datasets),
    "/",
    len(source_files)
)


print(
    "\nTABLEAU_SOURCE_INSPECTION_VALID: True"
)

=== Tableau Source Dataset Inspection ===

================================================================================
SOURCE: model_comparison_frozen_results.csv
Shape: (10, 13)
Columns:
['Model', 'Configuration', 'Accuracy', 'Churn Precision', 'Churn Recall', 'Churn F1', 'ROC-AUC', 'PR-AUC', 'CV PR-AUC', 'TN', 'FP', 'FN', 'TP']

Contents:

,Model,Configuration,Accuracy,Churn Precision,Churn Recall,Churn F1,ROC-AUC,PR-AUC,CV PR-AUC,TN,FP,FN,TP
0,Logistic Regression,Baseline,0.934950,0.000000,0.000000,0.000000,0.591996,0.086387,0.084810,1581,0,110,0
1,Logistic Regression,Imbalance-Aware,0.645772,0.086294,0.463636,0.145506,0.588103,0.081792,0.085750,1041,540,59,51
2,Decision Tree,Baseline,0.934358,0.000000,0.000000,0.000000,0.482865,0.065305,0.069525,1580,1,110,0
3,Decision Tree,Imbalance-Aware,0.649911,0.072695,0.372727,0.121662,0.518840,0.076944,0.069726,1058,523,69,41
4,Random Forest,Baseline,0.934950,0.000000,0.000000,0.000000,0.592048,0.087943,0.086859,1581,0,110,0
5,Random Forest,Imbalance-Aware,0.586635,0.078684,0.500000,0.135970,0.591202,0.101223,0.092939,937,644,55,55
6,XGBoost,Baseline,0.934950,0.000000,0.000000,0.000000,0.588554,0.082283,0.082594,1581,0,110,0
7,XGBoost,Imbalance-Aware,0.564755,0.077027,0.518182,0.134118,0.575838,0.085447,0.078534,898,683,53,57
8,LightGBM,Baseline,0.934950,0.000000,0.000000,0.000000,0.593203,0.084733,0.081180,1581,0,110,0
9,LightGBM,Imbalance-Aware,0.583678,0.087500,0.572727,0.151807,0.576209,0.083449,0.082526,924,657,47,63

================================================================================
SOURCE: imbalance_aware_model_ranking.csv
Shape: (5, 13)
Columns:
['Model', 'Churn Precision', 'Precision Rank', 'Churn Recall', 'Recall Rank', 'Churn F1', 'F1 Rank', 'ROC-AUC', 'ROC-AUC Rank', 'PR-AUC', 'PR-AUC Rank', 'FP', 'TP']

Contents:

,Model,Churn Precision,Precision Rank,Churn Recall,Recall Rank,Churn F1,F1 Rank,ROC-AUC,ROC-AUC Rank,PR-AUC,PR-AUC Rank,FP,TP
0,Logistic Regression,0.086294,2,0.463636,4,0.145506,2,0.588103,2,0.081792,4,540,51
1,Decision Tree,0.072695,5,0.372727,5,0.121662,5,0.518840,5,0.076944,5,523,41
2,Random Forest,0.078684,3,0.500000,3,0.135970,3,0.591202,1,0.101223,1,644,55
3,XGBoost,0.077027,4,0.518182,2,0.134118,4,0.575838,4,0.085447,2,683,57
4,LightGBM,0.087500,1,0.572727,1,0.151807,1,0.576209,3,0.083449,3,657,63

================================================================================
SOURCE: imbalance_aware_effect_comparison.csv
Shape: (5, 15)
Columns:
['Model', 'Baseline Accuracy', 'Imbalance Accuracy', 'Δ Accuracy', 'Baseline Recall', 'Imbalance Recall', 'Δ Recall', 'Baseline F1', 'Imbalance F1', 'Δ F1', 'Baseline PR-AUC', 'Imbalance PR-AUC', 'Δ PR-AUC', 'False Positives', 'True Positives']

Contents:

,Model,Baseline Accuracy,Imbalance Accuracy,Δ Accuracy,Baseline Recall,Imbalance Recall,Δ Recall,Baseline F1,Imbalance F1,Δ F1,Baseline PR-AUC,Imbalance PR-AUC,Δ PR-AUC,False Positives,True Positives
0,Logistic Regression,0.934950,0.645772,-0.289178,0.0,0.463636,0.463636,0.0,0.145506,0.145506,0.086387,0.081792,-0.004595,540,51
1,Decision Tree,0.934358,0.649911,-0.284447,0.0,0.372727,0.372727,0.0,0.121662,0.121662,0.065305,0.076944,0.011639,523,41
2,Random Forest,0.934950,0.586635,-0.348315,0.0,0.500000,0.500000,0.0,0.135970,0.135970,0.087943,0.101223,0.013280,644,55
3,XGBoost,0.934950,0.564755,-0.370195,0.0,0.518182,0.518182,0.0,0.134118,0.134118,0.082283,0.085447,0.003164,683,57
4,LightGBM,0.934950,0.583678,-0.351271,0.0,0.572727,0.572727,0.0,0.151807,0.151807,0.084733,0.083449,-0.001284,657,63

================================================================================
SOURCE: cross_model_explainability_ranks.csv
Shape: (24, 6)
Columns:
['Feature', 'Decision Tree Rank', 'Random Forest Rank', 'XGBoost Rank', 'LightGBM Rank', 'Mean Rank']

Contents:

,Feature,Decision Tree Rank,Random Forest Rank,XGBoost Rank,LightGBM Rank,Mean Rank
0,Average Mobile Revenue,1.0,1.0,1.0,1.0,1.000
1,ARPU,3.0,2.0,2.0,2.0,2.250
2,Active Subscribers,2.0,3.0,3.0,3.0,2.750
3,Inactive Subscriber Ratio,5.0,4.0,4.0,4.0,4.250
4,Inactive Subscribers,4.0,5.0,5.0,5.0,4.750
5,CRM Value Segment: Bronze,6.0,7.0,8.0,9.0,7.500
6,CRM Value Segment: Iron,8.0,10.0,6.0,8.0,8.000
7,Average Fixed Revenue,15.0,8.0,7.0,6.0,9.000
8,CRM Value Segment: Platinum,9.0,11.0,11.0,11.0,10.500
9,Effective Segment: VSE,7.0,6.0,17.0,14.0,11.000
10,CRM Value Segment: Silver,11.0,13.0,10.0,12.0,11.500
11,CRM Value Segment: SME,10.0,15.0,13.0,10.0,12.000
12,Effective Segment: SOHO,14.0,9.0,12.0,13.0,12.000
13,Effective Segment: SME,20.0,12.0,15.0,7.0,13.500
14,Suspended Subscribers,13.0,14.0,16.0,19.5,15.625
15,CRM Value Segment: Gold,12.0,16.0,18.0,19.5,16.375
16,CRM Value Segment: SE,20.0,21.5,9.0,19.5,17.500
17,CRM Value Segment: Lead,20.0,21.5,14.0,19.5,18.750
18,Effective Segment: Other,20.0,17.0,21.5,19.5,19.500
19,CRM Value Segment: Unknown,20.0,18.0,21.5,19.5,19.750
20,Effective Segment: LE,20.0,21.5,21.5,19.5,20.625
21,Effective Segment: SE,20.0,21.5,21.5,19.5,20.625
22,CRM Value Segment: Unseen category,20.0,21.5,21.5,19.5,20.625
23,Effective Segment: Unseen category,20.0,21.5,21.5,19.5,20.625

================================================================================
SOURCE: cross_model_perturbation_sensitivity.csv
Shape: (25, 8)
Columns:
['Model', 'Feature', 'Mean Absolute Probability Change', 'Perturbed ROC-AUC', 'ROC-AUC Change', 'Perturbed PR-AUC', 'PR-AUC Change', 'Sensitivity Rank']

Contents:

,Model,Feature,Mean Absolute Probability Change,Perturbed ROC-AUC,ROC-AUC Change,Perturbed PR-AUC,PR-AUC Change,Sensitivity Rank
0,Decision Tree,Average Mobile Revenue,0.264109,0.494256,-0.029323,0.063181,-0.018294,1
1,Decision Tree,Active Subscribers,0.136779,0.553594,0.030016,0.116145,0.034669,2
2,Decision Tree,ARPU,0.120700,0.517230,-0.006348,0.077924,-0.003552,3
3,Decision Tree,Inactive Subscriber Ratio,0.083604,0.477120,-0.046458,0.068647,-0.012828,4
4,Decision Tree,Inactive Subscribers,0.059761,0.519016,-0.004563,0.078375,-0.003100,5
5,LightGBM,Average Mobile Revenue,0.092403,0.483874,-0.092335,0.064430,-0.019019,1
6,LightGBM,ARPU,0.049312,0.559634,-0.016575,0.086972,0.003522,2
7,LightGBM,Active Subscribers,0.030497,0.551653,-0.024556,0.075726,-0.007724,3
8,LightGBM,Inactive Subscriber Ratio,0.018868,0.560221,-0.015988,0.080430,-0.003019,4
9,LightGBM,Inactive Subscribers,0.010975,0.566118,-0.010091,0.077957,-0.005493,5
10,Logistic Regression,Average Mobile Revenue,0.011432,0.478411,-0.109692,0.060775,-0.021017,1
11,Logistic Regression,ARPU,0.000000,0.588103,0.000000,0.081792,0.000000,2
12,Logistic Regression,Active Subscribers,0.000000,0.588103,0.000000,0.081792,0.000000,2
13,Logistic Regression,Inactive Subscriber Ratio,0.000000,0.588103,0.000000,0.081792,0.000000,2
14,Logistic Regression,Inactive Subscribers,0.000000,0.588103,0.000000,0.081792,0.000000,2
15,Random Forest,Average Mobile Revenue,0.055874,0.510767,-0.080435,0.080482,-0.020741,1
16,Random Forest,ARPU,0.016974,0.571779,-0.019424,0.082993,-0.018230,2
17,Random Forest,Active Subscribers,0.013404,0.581183,-0.010020,0.098609,-0.002614,3
18,Random Forest,Inactive Subscriber Ratio,0.011823,0.561515,-0.029688,0.085778,-0.015445,4
19,Random Forest,Inactive Subscribers,0.010159,0.586740,-0.004462,0.097821,-0.003403,5
20,XGBoost,Average Mobile Revenue,0.082141,0.515425,-0.060413,0.078518,-0.006930,1
21,XGBoost,ARPU,0.035288,0.556943,-0.018895,0.085587,0.000140,2
22,XGBoost,Active Subscribers,0.024408,0.561776,-0.014062,0.082404,-0.003043,3
23,XGBoost,Inactive Subscriber Ratio,0.015195,0.567926,-0.007912,0.081423,-0.004025,4
24,XGBoost,Inactive Subscribers,0.009482,0.569556,-0.006282,0.082529,-0.002918,5

================================================================================
SOURCE: cross_model_top_perturbation_feature.csv
Shape: (5, 5)
Columns:
['Model', 'Feature', 'Mean Absolute Probability Change', 'ROC-AUC Change', 'PR-AUC Change']

Contents:

,Model,Feature,Mean Absolute Probability Change,ROC-AUC Change,PR-AUC Change
0,Decision Tree,Average Mobile Revenue,0.264109,-0.029323,-0.018294
1,LightGBM,Average Mobile Revenue,0.092403,-0.092335,-0.019019
2,Logistic Regression,Average Mobile Revenue,0.011432,-0.109692,-0.021017
3,Random Forest,Average Mobile Revenue,0.055874,-0.080435,-0.020741
4,XGBoost,Average Mobile Revenue,0.082141,-0.060413,-0.006930

================================================================================
SOURCE: cross_model_explainability_summary.csv
Shape: (5, 6)
Columns:
['Model', 'Primary Explanation Method', 'Intrinsic / Post-hoc', 'Observed Model Complexity', 'Most Influential Feature', 'Explainability Scope Demonstrated']

Contents:

,Model,Primary Explanation Method,Intrinsic / Post-hoc,Observed Model Complexity,Most Influential Feature,Explainability Scope Demonstrated
0,Logistic Regression,Intrinsic coefficients,Intrinsic,1 non-zero coefficient from 24 inputs,Average Mobile Revenue,Global intrinsic
1,Decision Tree,Intrinsic rules + permutation SHAP,Intrinsic + post-hoc,Depth 10; 405 nodes,Average Mobile Revenue,Global intrinsic + global SHAP
2,Random Forest,Permutation SHAP,Post-hoc,50-tree ensemble,Average Mobile Revenue,Global SHAP
3,XGBoost,Native TreeSHAP,Post-hoc,50-tree boosted ensemble,Average Mobile Revenue,Global SHAP
4,LightGBM,Native TreeSHAP,Post-hoc,50-tree boosted ensemble,Average Mobile Revenue,Global + local SHAP

================================================================================
SOURCE: final_performance_interpretability_assessment.csv
Shape: (5, 13)
Columns:
['Model', 'Accuracy', 'Churn Precision', 'Churn Recall', 'Churn F1', 'ROC-AUC', 'PR-AUC', 'Interpretability Basis', 'Intrinsic Transparency', 'Fitted Model Complexity', 'Explanation Scope', 'Leading Explained Feature', 'Perturbation Rank-1 Feature']

Contents:

,Model,Accuracy,Churn Precision,Churn Recall,Churn F1,ROC-AUC,PR-AUC,Interpretability Basis,Intrinsic Transparency,Fitted Model Complexity,Explanation Scope,Leading Explained Feature,Perturbation Rank-1 Feature
0,Logistic Regression,0.6458,0.0863,0.4636,0.1455,0.5881,0.0818,Intrinsic coefficients,High,Sparse: 1/24 non-zero coefficients,Global intrinsic,Average Mobile Revenue,Average Mobile Revenue
1,Decision Tree,0.6499,0.0727,0.3727,0.1217,0.5188,0.0769,Intrinsic rules + permutation SHAP,Moderate,Depth 10; 405 nodes,Global intrinsic + global SHAP,Average Mobile Revenue,Average Mobile Revenue
2,Random Forest,0.5866,0.0787,0.5000,0.1360,0.5912,0.1012,Permutation SHAP,Low,50-tree ensemble,Global SHAP,Average Mobile Revenue,Average Mobile Revenue
3,XGBoost,0.5648,0.0770,0.5182,0.1341,0.5758,0.0854,Native TreeSHAP,Low,50-tree boosted ensemble,Global SHAP,Average Mobile Revenue,Average Mobile Revenue
4,LightGBM,0.5837,0.0875,0.5727,0.1518,0.5762,0.0834,Native TreeSHAP,Low,50-tree boosted ensemble,Global + local SHAP,Average Mobile Revenue,Average Mobile Revenue

================================================================================
SOURCE: qualitative_performance_interpretability_tradeoff.csv
Shape: (5, 5)
Columns:
['Model', 'Predictive Evidence', 'Interpretability Strength', 'Interpretability Limitation', 'Perturbation Evidence']

Contents:

,Model,Predictive Evidence,Interpretability Strength,Interpretability Limitation,Perturbation Evidence
0,Logistic Regression,"Second-highest churn F1; competitive ROC-AUC, ...",Highest intrinsic transparency; coefficients d...,Extremely sparse fitted representation: only 1...,Dependence restricted to Average Mobile Revenu...
1,Decision Tree,Weakest overall discrimination and lowest chur...,Decision rules intrinsically inspectable,"Depth-10, 405-node fitted tree limits practica...",High prediction sensitivity; some perturbation...
2,Random Forest,Highest ROC-AUC and PR-AUC; moderate churn rec...,Consistent global feature explanations through...,Ensemble is not intrinsically transparent; mod...,Stable feature ordering consistent with SHAP; ...
3,XGBoost,Second-highest churn recall and second-highest...,Efficient native TreeSHAP global explanations,Boosted ensemble is not intrinsically transpar...,Stable feature ordering consistent with SHAP; ...
4,LightGBM,"Highest churn precision, recall and F1; compet...",Efficient native TreeSHAP with both global and...,Boosted ensemble is not intrinsically transpar...,Stable feature ordering consistent with SHAP; ...

================================================================================
SOURCE: final_model_selection_evidence.csv
Shape: (10, 3)
Columns:
['Assessment Dimension', 'Evidence', 'Implication']

Contents:

,Assessment Dimension,Evidence,Implication
0,Churn Precision,LightGBM highest: 0.0875,Strongest threshold-based precision for identi...
1,Churn Recall,LightGBM highest: 0.5727,Recovered the largest proportion of actual chu...
2,Churn F1,LightGBM highest: 0.1518,Best observed balance of churn precision and r...
3,ROC-AUC,Random Forest highest: 0.5912; LightGBM: 0.5762,LightGBM did not lead this discrimination measure
4,PR-AUC,Random Forest highest: 0.1012; LightGBM: 0.0834,LightGBM did not lead this imbalance-sensitive...
5,Intrinsic Transparency,Logistic Regression strongest intrinsically; L...,Selection requires accepting lower intrinsic t...
6,Global Explainability,LightGBM supported efficient native TreeSHAP g...,Model complexity can be examined through effic...
7,Local Explainability,LightGBM demonstrated individual-level TreeSHA...,Individual predictions can be investigated in ...
8,Perturbation Consistency,LightGBM perturbation ordering broadly reinfor...,Independent sensitivity analysis provides comp...
9,Overall Performance–Interpretability Balance,LightGBM selected,Strongest overall balance under the evidence a...

================================================================================

=== Source Inventory Summary ===

,Source File,Rows,Columns,Duplicate Rows,Missing Cells
0,model_comparison_frozen_results.csv,10,13,0,0
1,imbalance_aware_model_ranking.csv,5,13,0,0
2,imbalance_aware_effect_comparison.csv,5,15,0,0
3,cross_model_explainability_ranks.csv,24,6,0,0
4,cross_model_perturbation_sensitivity.csv,25,8,0,0
5,cross_model_top_perturbation_feature.csv,5,5,0,0
6,cross_model_explainability_summary.csv,5,6,0,0
7,final_performance_interpretability_assessment.csv,5,13,0,0
8,qualitative_performance_interpretability_trade...,5,5,0,0
9,final_model_selection_evidence.csv,10,3,0,0

Sources successfully loaded: 10 / 10

TABLEAU_SOURCE_INSPECTION_VALID: True

In [ ]:
# ============================================================
# Cell 3 — Discover Authoritative Prepared Dataset
# ============================================================

import os


print("=== Prepared Dataset Discovery ===\n")


# ------------------------------------------------------------
# Search dissertation project for Parquet artefacts
# ------------------------------------------------------------

parquet_candidates = []


for root, dirs, files in os.walk(
    PROJECT
):

    # Avoid descending into frozen model directories
    if "frozen_final_models" in root:
        continue

    # Spark Parquet datasets are directories containing
    # one or more part-* files.
    if any(
        filename.startswith("part-")
        for filename in files
    ):

        parquet_candidates.append(
            root
        )


parquet_candidates = sorted(
    set(parquet_candidates)
)


print(
    "Parquet-style dataset directories discovered:",
    len(parquet_candidates)
)


for i, path in enumerate(
    parquet_candidates,
    start=1
):

    print(
        f"{i:>2}. {path}"
    )


# ------------------------------------------------------------
# Also inspect dataset directory
# ------------------------------------------------------------

print(
    "\n=== Dataset Directory Contents ==="
)


dataset_items = sorted(
    os.listdir(DATA)
)


for item in dataset_items:

    path = os.path.join(
        DATA,
        item
    )

    item_type = (
        "DIR"
        if os.path.isdir(path)
        else "FILE"
    )

    print(
        f"{item_type:<5}  {item}"
    )


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert os.path.exists(
    DATA
)

assert len(
    dataset_items
) > 0


print(
    "\nPREPARED_DATASET_DISCOVERY_VALID: True"
)

=== Prepared Dataset Discovery ===

Parquet-style dataset directories discovered: 15
 1. /content/drive/MyDrive/7005SCN_Dissertation/models/categorical_preprocessing/metadata
 2. /content/drive/MyDrive/7005SCN_Dissertation/models/categorical_preprocessing/stages/0_StringIndexer_196ac2591a3f/data
 3. /content/drive/MyDrive/7005SCN_Dissertation/models/categorical_preprocessing/stages/0_StringIndexer_196ac2591a3f/metadata
 4. /content/drive/MyDrive/7005SCN_Dissertation/models/categorical_preprocessing/stages/1_StringIndexer_e0f5bf3a8b61/data
 5. /content/drive/MyDrive/7005SCN_Dissertation/models/categorical_preprocessing/stages/1_StringIndexer_e0f5bf3a8b61/metadata
 6. /content/drive/MyDrive/7005SCN_Dissertation/models/categorical_preprocessing/stages/2_OneHotEncoder_378dfeb1105f/data
 7. /content/drive/MyDrive/7005SCN_Dissertation/models/categorical_preprocessing/stages/2_OneHotEncoder_378dfeb1105f/metadata
 8. /content/drive/MyDrive/7005SCN_Dissertation/models/logistic_scaler/data
 9. /content/drive/MyDrive/7005SCN_Dissertation/models/logistic_scaler/metadata
10. /content/drive/MyDrive/7005SCN_Dissertation/outputs/test_lr_features
11. /content/drive/MyDrive/7005SCN_Dissertation/outputs/test_tree_features
12. /content/drive/MyDrive/7005SCN_Dissertation/outputs/train_lr_features
13. /content/drive/MyDrive/7005SCN_Dissertation/outputs/train_lr_features_weighted
14. /content/drive/MyDrive/7005SCN_Dissertation/outputs/train_tree_features
15. /content/drive/MyDrive/7005SCN_Dissertation/outputs/train_tree_features_weighted

=== Dataset Directory Contents ===
FILE   Baza_customer_Telecom_v2.csv

PREPARED_DATASET_DISCOVERY_VALID: True

In [ ]:
# ============================================================
# Cell 4 — Load and Standardise Customer-Level Tableau Source
# ============================================================

import os
import pandas as pd


print("=== Customer-Level Tableau Source Inspection ===\n")


# ------------------------------------------------------------
# Load authoritative raw dataset
# ------------------------------------------------------------

CSV_PATH = os.path.join(
    DATA,
    "Baza_customer_Telecom_v2.csv"
)

assert os.path.exists(CSV_PATH)

df_tableau_raw = pd.read_csv(CSV_PATH)


print(
    "Raw shape:",
    df_tableau_raw.shape
)


# ------------------------------------------------------------
# Standardise column names
# Reproduces the column-name cleaning established in Notebook 1
# ------------------------------------------------------------

original_columns = list(
    df_tableau_raw.columns
)

df_tableau_raw.columns = (
    df_tableau_raw.columns
    .str.strip()
)


print(
    "\n=== Column Name Standardisation ===\n"
)


for old, new in zip(
    original_columns,
    df_tableau_raw.columns
):

    status = (
        "CHANGED"
        if old != new
        else "unchanged"
    )

    print(
        f"{repr(old):<30} -> "
        f"{repr(new):<30} "
        f"[{status}]"
    )


# Column names must now be unique
assert (
    df_tableau_raw.columns.is_unique
)


# ------------------------------------------------------------
# Schema after standardisation
# ------------------------------------------------------------

schema_df = pd.DataFrame({

    "Column":
        df_tableau_raw.columns,

    "Data Type":
        [
            str(dtype)
            for dtype
            in df_tableau_raw.dtypes
        ],

    "Missing":
        [
            int(
                df_tableau_raw[col]
                .isna()
                .sum()
            )
            for col
            in df_tableau_raw.columns
        ],

    "Unique Values":
        [
            int(
                df_tableau_raw[col]
                .nunique(dropna=True)
            )
            for col
            in df_tableau_raw.columns
        ]
})


print(
    "\n=== Standardised Schema ===\n"
)

display(
    schema_df
)


# ------------------------------------------------------------
# Target distribution
# ------------------------------------------------------------

churn_counts = (
    df_tableau_raw["CHURN"]
    .value_counts(dropna=False)
    .rename_axis("CHURN")
    .reset_index(name="Count")
)


churn_counts[
    "Percentage"
] = (
    churn_counts["Count"]
    / len(df_tableau_raw)
    * 100
)


print(
    "\n=== CHURN Distribution ===\n"
)

display(
    churn_counts
)


# ------------------------------------------------------------
# Relevant categorical values
# ------------------------------------------------------------

print(
    "\n=== Relevant Categorical Values ==="
)


for col in [
    "CRM_PID_Value_Segment",
    "EffectiveSegment"
]:

    print(
        f"\n{col}:"
    )

    print(
        sorted(
            df_tableau_raw[col]
            .dropna()
            .astype(str)
            .unique()
            .tolist()
        )
    )


# ------------------------------------------------------------
# Fields required for established Notebook 1 reconstruction
# ------------------------------------------------------------

reconstruction_fields = [

    "Active_subscribers",
    "Not_Active_subscribers",
    "Suspended_subscribers",
    "Total_SUBs",

    "AvgMobileRevenue",
    "AvgFIXRevenue",
    "TotalRevenue",
    "ARPU"
]


print(
    "\n=== Reconstruction Field Audit ===\n"
)


reconstruction_audit = []


for col in reconstruction_fields:

    assert col in df_tableau_raw.columns, (
        f"Required field missing: {repr(col)}"
    )

    reconstruction_audit.append({

        "Field":
            col,

        "Missing":
            int(
                df_tableau_raw[col]
                .isna()
                .sum()
            ),

        "Non-Missing":
            int(
                df_tableau_raw[col]
                .notna()
                .sum()
            )
    })


display(
    pd.DataFrame(
        reconstruction_audit
    )
)


# ------------------------------------------------------------
# Authoritative dataset validation
# ------------------------------------------------------------

assert df_tableau_raw.shape == (
    8453,
    14
)


target_counts = (
    df_tableau_raw["CHURN"]
    .value_counts()
)


assert target_counts.get(
    "No",
    0
) == 7904


assert target_counts.get(
    "Yes",
    0
) == 549


# Confirm known raw-data issues from Notebook 1
assert (
    df_tableau_raw[
        "CRM_PID_Value_Segment"
    ]
    .eq("Sliver")
    .any()
)


print(
    "\n=== Validation ==="
)

print(
    "Rows:",
    len(df_tableau_raw)
)

print(
    "Non-churn:",
    target_counts["No"]
)

print(
    "Churn:",
    target_counts["Yes"]
)

print(
    "Churn rate:",
    f"{target_counts['Yes'] / len(df_tableau_raw):.4%}"
)

print(
    "Known 'Sliver' category present:",
    True
)


print(
    "\nCUSTOMER_SOURCE_INSPECTION_VALID: True"
)

=== Customer-Level Tableau Source Inspection ===

Raw shape: (8453, 14)

=== Column Name Standardisation ===

'PID'                          -> 'PID'                          [unchanged]
'CRM_PID_Value_Segment'        -> 'CRM_PID_Value_Segment'        [unchanged]
'EffectiveSegment'             -> 'EffectiveSegment'             [unchanged]
'Billing_ZIP'                  -> 'Billing_ZIP'                  [unchanged]
'KA_name'                      -> 'KA_name'                      [unchanged]
'Active_subscribers'           -> 'Active_subscribers'           [unchanged]
'Not_Active_subscribers'       -> 'Not_Active_subscribers'       [unchanged]
'Suspended_subscribers'        -> 'Suspended_subscribers'        [unchanged]
'Total_SUBs'                   -> 'Total_SUBs'                   [unchanged]
'AvgMobileRevenue '            -> 'AvgMobileRevenue'             [CHANGED]
'AvgFIXRevenue'                -> 'AvgFIXRevenue'                [unchanged]
'TotalRevenue'                 -> 'TotalRevenue'                 [unchanged]
'ARPU'                         -> 'ARPU'                         [unchanged]
'CHURN'                        -> 'CHURN'                        [unchanged]

=== Standardised Schema ===

                    Column Data Type  Missing  Unique Values
0                      PID    object        0           8436
1    CRM_PID_Value_Segment    object        5              9
2         EffectiveSegment    object        0              6
3              Billing_ZIP   float64        2            456
4                  KA_name    object        0             12
5       Active_subscribers     int64        0             61
6   Not_Active_subscribers   float64     4149             60
7    Suspended_subscribers   float64     8101             13
8               Total_SUBs     int64        0             89
9         AvgMobileRevenue   float64        0           2150
10           AvgFIXRevenue   float64        0            106
11            TotalRevenue   float64        0           2163
12                    ARPU   float64        1           3063
13                   CHURN    object        0              2

=== CHURN Distribution ===

  CHURN  Count  Percentage
0    No   7904   93.505264
1   Yes    549    6.494736

=== Relevant Categorical Values ===

CRM_PID_Value_Segment:
['Bronze', 'Gold', 'Iron', 'Lead', 'Platinum', 'SE', 'SME', 'Silver', 'Sliver']

EffectiveSegment:
['LE', 'Other', 'SE', 'SME', 'SOHO', 'VSE']

=== Reconstruction Field Audit ===

                    Field  Missing  Non-Missing
0      Active_subscribers        0         8453
1  Not_Active_subscribers     4149         4304
2   Suspended_subscribers     8101          352
3              Total_SUBs        0         8453
4        AvgMobileRevenue        0         8453
5           AvgFIXRevenue        0         8453
6            TotalRevenue        0         8453
7                    ARPU        1         8452

=== Validation ===
Rows: 8453
Non-churn: 7904
Churn: 549
Churn rate: 6.4947%
Known 'Sliver' category present: True

CUSTOMER_SOURCE_INSPECTION_VALID: True

In [ ]:
# ============================================================
# Cell 5 — Reproduce Validated Notebook 1 Cleaning for Tableau
# ============================================================

import numpy as np
import pandas as pd


print("=== Tableau Customer Data Cleaning ===\n")


# ------------------------------------------------------------
# Work from a copy of the standardised raw dataset
# ------------------------------------------------------------

df_tableau_clean = (
    df_tableau_raw
    .copy()
)


# ------------------------------------------------------------
# 1. Correct known categorical typo
# ------------------------------------------------------------

sliver_before = int(
    (
        df_tableau_clean[
            "CRM_PID_Value_Segment"
        ] == "Sliver"
    ).sum()
)


df_tableau_clean[
    "CRM_PID_Value_Segment"
] = (
    df_tableau_clean[
        "CRM_PID_Value_Segment"
    ]
    .replace({
        "Sliver": "Silver"
    })
)


sliver_after = int(
    (
        df_tableau_clean[
            "CRM_PID_Value_Segment"
        ] == "Sliver"
    ).sum()
)


# ------------------------------------------------------------
# 2. Missing CRM segment -> Unknown
# ------------------------------------------------------------

crm_missing_before = int(
    df_tableau_clean[
        "CRM_PID_Value_Segment"
    ]
    .isna()
    .sum()
)


df_tableau_clean[
    "CRM_PID_Value_Segment"
] = (
    df_tableau_clean[
        "CRM_PID_Value_Segment"
    ]
    .fillna("Unknown")
)


# ------------------------------------------------------------
# 3. Reconstruct subscriber-count missingness
#
# Total_SUBs =
# Active + Not Active + Suspended
#
# Notebook 1 established this deterministic relationship.
# ------------------------------------------------------------

inactive_missing_before = int(
    df_tableau_clean[
        "Not_Active_subscribers"
    ]
    .isna()
    .sum()
)


suspended_missing_before = int(
    df_tableau_clean[
        "Suspended_subscribers"
    ]
    .isna()
    .sum()
)


# Missing inactive counts:
# infer using Total - Active - Suspended,
# treating missing suspended as zero for reconstruction.

inactive_mask = (
    df_tableau_clean[
        "Not_Active_subscribers"
    ]
    .isna()
)


df_tableau_clean.loc[
    inactive_mask,
    "Not_Active_subscribers"
] = (

    df_tableau_clean.loc[
        inactive_mask,
        "Total_SUBs"
    ]

    -

    df_tableau_clean.loc[
        inactive_mask,
        "Active_subscribers"
    ]

    -

    df_tableau_clean.loc[
        inactive_mask,
        "Suspended_subscribers"
    ]
    .fillna(0)
)


# Missing suspended counts can now be reconstructed
# from the same accounting identity.

suspended_mask = (
    df_tableau_clean[
        "Suspended_subscribers"
    ]
    .isna()
)


df_tableau_clean.loc[
    suspended_mask,
    "Suspended_subscribers"
] = (

    df_tableau_clean.loc[
        suspended_mask,
        "Total_SUBs"
    ]

    -

    df_tableau_clean.loc[
        suspended_mask,
        "Active_subscribers"
    ]

    -

    df_tableau_clean.loc[
        suspended_mask,
        "Not_Active_subscribers"
    ]
)


# ------------------------------------------------------------
# 4. Reconstruct the single missing ARPU value
#
# Notebook 1 established:
# TotalRevenue = 40.17
# Total_SUBs = 2
# ARPU = 20.085 -> 20.09
# ------------------------------------------------------------

arpu_missing_before = int(
    df_tableau_clean[
        "ARPU"
    ]
    .isna()
    .sum()
)


arpu_mask = (
    df_tableau_clean[
        "ARPU"
    ]
    .isna()
)


df_tableau_clean.loc[
    arpu_mask,
    "ARPU"
] = (

    df_tableau_clean.loc[
        arpu_mask,
        "TotalRevenue"
    ]

    /

    df_tableau_clean.loc[
        arpu_mask,
        "Total_SUBs"
    ]

).round(2)


# ------------------------------------------------------------
# 5. Recreate established descriptive ratio
# ------------------------------------------------------------

df_tableau_clean[
    "Inactive_Ratio"
] = np.where(

    df_tableau_clean[
        "Total_SUBs"
    ] > 0,

    df_tableau_clean[
        "Not_Active_subscribers"
    ]

    /

    df_tableau_clean[
        "Total_SUBs"
    ],

    0.0
)


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

subscriber_identity_error = (

    df_tableau_clean[
        "Total_SUBs"
    ]

    -

    (
        df_tableau_clean[
            "Active_subscribers"
        ]

        +

        df_tableau_clean[
            "Not_Active_subscribers"
        ]

        +

        df_tableau_clean[
            "Suspended_subscribers"
        ]
    )
).abs()


print("=== Cleaning Audit ===")

print(
    "Sliver values corrected:",
    sliver_before
)

print(
    "Sliver values remaining:",
    sliver_after
)

print(
    "Missing CRM values filled:",
    crm_missing_before
)

print(
    "Missing inactive counts reconstructed:",
    inactive_missing_before
)

print(
    "Missing suspended counts reconstructed:",
    suspended_missing_before
)

print(
    "Missing ARPU values reconstructed:",
    arpu_missing_before
)


print(
    "\n=== Post-Cleaning Validation ==="
)

print(
    "Rows:",
    len(df_tableau_clean)
)

print(
    "Total missing cells:",
    int(
        df_tableau_clean
        .isna()
        .sum()
        .sum()
    )
)

print(
    "Maximum subscriber identity error:",
    float(
        subscriber_identity_error.max()
    )
)

print(
    "Minimum Inactive_Ratio:",
    float(
        df_tableau_clean[
            "Inactive_Ratio"
        ].min()
    )
)

print(
    "Maximum Inactive_Ratio:",
    float(
        df_tableau_clean[
            "Inactive_Ratio"
        ].max()
    )
)


# ------------------------------------------------------------
# Assertions
# ------------------------------------------------------------

assert len(
    df_tableau_clean
) == 8453

assert sliver_after == 0

assert (
    df_tableau_clean[
        "CRM_PID_Value_Segment"
    ]
    .isna()
    .sum()
    == 0
)

assert (
    df_tableau_clean[
        reconstruction_fields
    ]
    .isna()
    .sum()
    .sum()
    == 0
)

assert np.allclose(
    subscriber_identity_error,
    0
)

assert (
    df_tableau_clean[
        "ARPU"
    ]
    .isna()
    .sum()
    == 0
)

assert (
    df_tableau_clean[
        "CHURN"
    ]
    .value_counts()
    .get("Yes", 0)
    == 549
)


print(
    "\nTABLEAU_CUSTOMER_CLEANING_VALID: True"
)

=== Tableau Customer Data Cleaning ===

=== Cleaning Audit ===
Sliver values corrected: 1
Sliver values remaining: 0
Missing CRM values filled: 5
Missing inactive counts reconstructed: 4149
Missing suspended counts reconstructed: 8101
Missing ARPU values reconstructed: 1

=== Post-Cleaning Validation ===
Rows: 8453
Total missing cells: 2
Maximum subscriber identity error: 0.0
Minimum Inactive_Ratio: 0.0
Maximum Inactive_Ratio: 0.99375

TABLEAU_CUSTOMER_CLEANING_VALID: True

In [ ]:
# ============================================================
# Cell 6 — Tableau Dashboard 1 Exports
# Dataset and Churn Profile
# ============================================================

import os
import pandas as pd


print("=== Dashboard 1: Dataset and Churn Profile ===\n")


# ------------------------------------------------------------
# 1. Dataset summary / KPI file
# ------------------------------------------------------------

total_customers = len(
    df_tableau_clean
)

churn_customers = int(
    (
        df_tableau_clean["CHURN"] == "Yes"
    ).sum()
)

non_churn_customers = int(
    (
        df_tableau_clean["CHURN"] == "No"
    ).sum()
)

churn_rate = (
    churn_customers
    / total_customers
)


d1_summary = pd.DataFrame([{

    "Total Customers":
        total_customers,

    "Churn Customers":
        churn_customers,

    "Non-Churn Customers":
        non_churn_customers,

    "Churn Rate":
        churn_rate,

    "Non-Churn Rate":
        non_churn_customers / total_customers,

    "Original Variables":
        14,

    "Model Predictors":
        9,

    "Final Encoded Inputs":
        24
}])


# ------------------------------------------------------------
# 2. Churn distribution
# ------------------------------------------------------------

d1_churn_distribution = (
    df_tableau_clean[
        "CHURN"
    ]
    .value_counts()
    .rename_axis(
        "Churn Status"
    )
    .reset_index(
        name="Customer Count"
    )
)


d1_churn_distribution[
    "Percentage"
] = (
    d1_churn_distribution[
        "Customer Count"
    ]
    / total_customers
)


# ------------------------------------------------------------
# 3. CRM value segment × churn
# ------------------------------------------------------------

d1_crm_segment = (
    df_tableau_clean
    .groupby(
        [
            "CRM_PID_Value_Segment",
            "CHURN"
        ],
        dropna=False
    )
    .size()
    .reset_index(
        name="Customer Count"
    )
    .rename(
        columns={
            "CRM_PID_Value_Segment":
                "CRM Value Segment",

            "CHURN":
                "Churn Status"
        }
    )
)


crm_totals = (
    d1_crm_segment
    .groupby(
        "CRM Value Segment"
    )[
        "Customer Count"
    ]
    .transform("sum")
)


d1_crm_segment[
    "Within-Segment Percentage"
] = (
    d1_crm_segment[
        "Customer Count"
    ]
    / crm_totals
)


# ------------------------------------------------------------
# 4. Effective segment × churn
# ------------------------------------------------------------

d1_effective_segment = (
    df_tableau_clean
    .groupby(
        [
            "EffectiveSegment",
            "CHURN"
        ],
        dropna=False
    )
    .size()
    .reset_index(
        name="Customer Count"
    )
    .rename(
        columns={
            "EffectiveSegment":
                "Effective Segment",

            "CHURN":
                "Churn Status"
        }
    )
)


effective_totals = (
    d1_effective_segment
    .groupby(
        "Effective Segment"
    )[
        "Customer Count"
    ]
    .transform("sum")
)


d1_effective_segment[
    "Within-Segment Percentage"
] = (
    d1_effective_segment[
        "Customer Count"
    ]
    / effective_totals
)


# ------------------------------------------------------------
# 5. Numerical profile by churn status
#
# Descriptive only — no new modelling/inference.
# ------------------------------------------------------------

profile_features = {

    "Active_subscribers":
        "Active Subscribers",

    "Not_Active_subscribers":
        "Inactive Subscribers",

    "Suspended_subscribers":
        "Suspended Subscribers",

    "AvgMobileRevenue":
        "Average Mobile Revenue",

    "AvgFIXRevenue":
        "Average Fixed Revenue",

    "ARPU":
        "ARPU",

    "Inactive_Ratio":
        "Inactive Subscriber Ratio"
}


profile_rows = []


for source_col, display_name in profile_features.items():

    for churn_status, group in (
        df_tableau_clean
        .groupby("CHURN")
    ):

        profile_rows.append({

            "Feature":
                display_name,

            "Churn Status":
                churn_status,

            "Customer Count":
                len(group),

            "Mean":
                group[source_col].mean(),

            "Median":
                group[source_col].median(),

            "Standard Deviation":
                group[source_col].std(),

            "Minimum":
                group[source_col].min(),

            "Maximum":
                group[source_col].max()
        })


d1_numeric_profile = pd.DataFrame(
    profile_rows
)


# ------------------------------------------------------------
# Export paths
# ------------------------------------------------------------

d1_files = {

    "tableau_d1_dataset_summary.csv":
        d1_summary,

    "tableau_d1_churn_distribution.csv":
        d1_churn_distribution,

    "tableau_d1_crm_segment_churn.csv":
        d1_crm_segment,

    "tableau_d1_effective_segment_churn.csv":
        d1_effective_segment,

    "tableau_d1_numeric_profile.csv":
        d1_numeric_profile
}


# ------------------------------------------------------------
# Write Tableau-ready CSVs
# ------------------------------------------------------------

for filename, df in d1_files.items():

    filepath = os.path.join(
        TABLEAU,
        filename
    )

    df.to_csv(
        filepath,
        index=False
    )


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert int(
    d1_summary.loc[
        0,
        "Total Customers"
    ]
) == 8453


assert int(
    d1_summary.loc[
        0,
        "Churn Customers"
    ]
) == 549


assert (
    d1_churn_distribution[
        "Customer Count"
    ].sum()
    == 8453
)


assert (
    d1_crm_segment[
        "Customer Count"
    ].sum()
    == 8453
)


assert (
    d1_effective_segment[
        "Customer Count"
    ].sum()
    == 8453
)


assert len(
    d1_numeric_profile
) == 14


# ------------------------------------------------------------
# Report exports
# ------------------------------------------------------------

print("=== Dashboard 1 Export Audit ===\n")


audit_rows = []


for filename, df in d1_files.items():

    filepath = os.path.join(
        TABLEAU,
        filename
    )

    audit_rows.append({

        "File":
            filename,

        "Rows":
            len(df),

        "Columns":
            len(df.columns),

        "Missing Cells":
            int(
                df.isna()
                .sum()
                .sum()
            ),

        "Size (bytes)":
            os.path.getsize(
                filepath
            )
    })


d1_export_audit = pd.DataFrame(
    audit_rows
)


display(
    d1_export_audit
)


print(
    "\n=== Dataset Summary ===\n"
)

display(
    d1_summary
)


print(
    "\n=== Churn Distribution ===\n"
)

display(
    d1_churn_distribution
)


print(
    "\n=== CRM Segment × Churn ===\n"
)

display(
    d1_crm_segment
)


print(
    "\n=== Effective Segment × Churn ===\n"
)

display(
    d1_effective_segment
)


print(
    "\nTABLEAU_DASHBOARD_1_EXPORT_VALID: True"
)

=== Dashboard 1: Dataset and Churn Profile ===

=== Dashboard 1 Export Audit ===

,File,Rows,Columns,Missing Cells,Size (bytes)
0,tableau_d1_dataset_summary.csv,1,8,0,196
1,tableau_d1_churn_distribution.csv,2,3,0,94
2,tableau_d1_crm_segment_churn.csv,16,4,0,556
3,tableau_d1_effective_segment_churn.csv,11,4,0,394
4,tableau_d1_numeric_profile.csv,14,8,0,1248

=== Dataset Summary ===

,Total Customers,Churn Customers,Non-Churn Customers,Churn Rate,Non-Churn Rate,Original Variables,Model Predictors,Final Encoded Inputs
0,8453,549,7904,0.064947,0.935053,14,9,24

=== Churn Distribution ===

  Churn Status  Customer Count  Percentage
0           No            7904    0.935053
1          Yes             549    0.064947

=== CRM Segment × Churn ===

   CRM Value Segment Churn Status  Customer Count  Within-Segment Percentage
0             Bronze           No            3615                   0.946335
1             Bronze          Yes             205                   0.053665
2               Gold           No            1336                   0.919477
3               Gold          Yes             117                   0.080523
4               Iron           No             237                   0.963415
5               Iron          Yes               9                   0.036585
6               Lead           No              27                   1.000000
7           Platinum           No             491                   0.914339
8           Platinum          Yes              46                   0.085661
9                 SE           No              40                   0.975610
10                SE          Yes               1                   0.024390
11               SME           No             259                   0.911972
12               SME          Yes              25                   0.088028
13            Silver           No            1894                   0.928431
14            Silver          Yes             146                   0.071569
15           Unknown           No               5                   1.000000

=== Effective Segment × Churn ===

   Effective Segment Churn Status  Customer Count  Within-Segment Percentage
0                 LE           No               2                   1.000000
1              Other           No              27                   0.931034
2              Other          Yes               2                   0.068966
3                 SE           No              41                   0.976190
4                 SE          Yes               1                   0.023810
5                SME           No             259                   0.911972
6                SME          Yes              25                   0.088028
7               SOHO           No            5939                   0.942549
8               SOHO          Yes             362                   0.057451
9                VSE           No            1636                   0.911421
10               VSE          Yes             159                   0.088579

TABLEAU_DASHBOARD_1_EXPORT_VALID: True

### Dashboard 1 Export Interpretation

Five Tableau-ready datasets were generated to support the **Dataset and Churn Profile** dashboard. These exports describe the dataset used throughout the dissertation and do not introduce any additional modelling or model-selection decisions.

The dataset contains **8,453 telecommunications business customers**, of whom **549 (6.49%)** are recorded as churners and **7,904 (93.51%)** as non-churners. This substantial class imbalance provides important context for the subsequent model evaluation and explains why accuracy is treated primarily as a contextual metric rather than the principal measure of churn-prediction performance.

The exported segment-level datasets allow churn counts and within-segment proportions to be visualised across CRM Value Segment and Effective Segment. These summaries are descriptive and should be interpreted cautiously for categories containing relatively few observations.

A separate numerical profile summarises the retained subscriber and revenue characteristics by churn status. These comparisons are intended to communicate characteristics of the analysed sample and should not be interpreted as evidence of causal relationships between individual features and customer churn.

All Dashboard 1 exports were derived from the same source dataset and cleaning rules established in Notebook 1. No models were trained, tuned or modified during Tableau preparation.

In [ ]:
# ============================================================
# Cell 7 — Tableau Dashboard 2 Exports
# Comparative Model Performance
# ============================================================

import os
import pandas as pd


print("=== Dashboard 2: Comparative Model Performance ===\n")


# ------------------------------------------------------------
# Load authoritative frozen model results
# ------------------------------------------------------------

performance_source_path = os.path.join(
    OUTPUTS,
    "model_comparison_frozen_results.csv"
)


assert os.path.exists(
    performance_source_path
)


performance_source = pd.read_csv(
    performance_source_path
)


# ------------------------------------------------------------
# Retain the five frozen imbalance-aware configurations
# ------------------------------------------------------------

d2_performance = (
    performance_source[
        performance_source[
            "Configuration"
        ] == "Imbalance-Aware"
    ]
    .copy()
    .reset_index(drop=True)
)


expected_models = [
    "Logistic Regression",
    "Decision Tree",
    "Random Forest",
    "XGBoost",
    "LightGBM"
]


assert set(
    d2_performance["Model"]
) == set(
    expected_models
)


assert len(
    d2_performance
) == 5


# Preserve dissertation model order
d2_performance[
    "Model"
] = pd.Categorical(
    d2_performance["Model"],
    categories=expected_models,
    ordered=True
)


d2_performance = (
    d2_performance
    .sort_values("Model")
    .reset_index(drop=True)
)


# Convert back to normal strings for clean CSV import
d2_performance[
    "Model"
] = d2_performance[
    "Model"
].astype(str)


# ------------------------------------------------------------
# 1. Wide performance comparison
# ------------------------------------------------------------

performance_columns = [
    "Model",
    "Configuration",
    "Accuracy",
    "Churn Precision",
    "Churn Recall",
    "Churn F1",
    "ROC-AUC",
    "PR-AUC",
    "CV PR-AUC",
    "TN",
    "FP",
    "FN",
    "TP"
]


d2_performance_wide = (
    d2_performance[
        performance_columns
    ]
    .copy()
)


# ------------------------------------------------------------
# 2. Long-form metric dataset
#
# Better suited to grouped bars, dot plots and metric filters
# in Tableau.
# ------------------------------------------------------------

metric_columns = [
    "Accuracy",
    "Churn Precision",
    "Churn Recall",
    "Churn F1",
    "ROC-AUC",
    "PR-AUC",
    "CV PR-AUC"
]


d2_metrics_long = (
    d2_performance_wide[
        ["Model"] + metric_columns
    ]
    .melt(
        id_vars="Model",
        var_name="Metric",
        value_name="Value"
    )
)


# Add metric interpretation category for dashboard filtering
metric_type_map = {

    "Accuracy":
        "Context",

    "Churn Precision":
        "Churn Classification",

    "Churn Recall":
        "Churn Classification",

    "Churn F1":
        "Churn Classification",

    "ROC-AUC":
        "Discrimination",

    "PR-AUC":
        "Discrimination",

    "CV PR-AUC":
        "Cross-Validation"
}


d2_metrics_long[
    "Metric Group"
] = (
    d2_metrics_long[
        "Metric"
    ]
    .map(metric_type_map)
)


# ------------------------------------------------------------
# 3. Tidy confusion-matrix dataset
# ------------------------------------------------------------

confusion_rows = []


for _, row in d2_performance_wide.iterrows():

    confusion_rows.extend([

        {
            "Model": row["Model"],
            "Actual Class": "Non-Churn",
            "Predicted Class": "Non-Churn",
            "Outcome": "True Negative",
            "Count": int(row["TN"])
        },

        {
            "Model": row["Model"],
            "Actual Class": "Non-Churn",
            "Predicted Class": "Churn",
            "Outcome": "False Positive",
            "Count": int(row["FP"])
        },

        {
            "Model": row["Model"],
            "Actual Class": "Churn",
            "Predicted Class": "Non-Churn",
            "Outcome": "False Negative",
            "Count": int(row["FN"])
        },

        {
            "Model": row["Model"],
            "Actual Class": "Churn",
            "Predicted Class": "Churn",
            "Outcome": "True Positive",
            "Count": int(row["TP"])
        }
    ])


d2_confusion_matrix = pd.DataFrame(
    confusion_rows
)


# ------------------------------------------------------------
# Validation against held-out test-set structure
# ------------------------------------------------------------

for model in expected_models:

    model_cm = d2_confusion_matrix[
        d2_confusion_matrix[
            "Model"
        ] == model
    ]

    assert (
        model_cm["Count"].sum()
        == 1691
    )

    actual_churn = (
        model_cm.loc[
            model_cm[
                "Actual Class"
            ] == "Churn",
            "Count"
        ].sum()
    )

    actual_non_churn = (
        model_cm.loc[
            model_cm[
                "Actual Class"
            ] == "Non-Churn",
            "Count"
        ].sum()
    )

    assert actual_churn == 110
    assert actual_non_churn == 1581


# ------------------------------------------------------------
# Export
# ------------------------------------------------------------

d2_files = {

    "tableau_d2_model_performance.csv":
        d2_performance_wide,

    "tableau_d2_metrics_long.csv":
        d2_metrics_long,

    "tableau_d2_confusion_matrix.csv":
        d2_confusion_matrix
}


for filename, df in d2_files.items():

    filepath = os.path.join(
        TABLEAU,
        filename
    )

    df.to_csv(
        filepath,
        index=False
    )


# ------------------------------------------------------------
# Export audit
# ------------------------------------------------------------

audit_rows = []


for filename, df in d2_files.items():

    filepath = os.path.join(
        TABLEAU,
        filename
    )

    audit_rows.append({

        "File":
            filename,

        "Rows":
            len(df),

        "Columns":
            len(df.columns),

        "Missing Cells":
            int(
                df.isna()
                .sum()
                .sum()
            ),

        "Size (bytes)":
            os.path.getsize(
                filepath
            )
    })


d2_export_audit = pd.DataFrame(
    audit_rows
)


print(
    "=== Dashboard 2 Export Audit ===\n"
)

display(
    d2_export_audit
)


print(
    "\n=== Frozen Imbalance-Aware Model Performance ===\n"
)

display(
    d2_performance_wide
)


print(
    "\n=== Long-Form Metrics Preview ===\n"
)

display(
    d2_metrics_long.head(15)
)


print(
    "\n=== Confusion Matrix Dataset ===\n"
)

display(
    d2_confusion_matrix
)


# ------------------------------------------------------------
# Final validation
# ------------------------------------------------------------

assert len(
    d2_performance_wide
) == 5

assert len(
    d2_metrics_long
) == 35

assert len(
    d2_confusion_matrix
) == 20

assert (
    d2_export_audit[
        "Missing Cells"
    ].sum()
    == 0
)


print(
    "\nTABLEAU_DASHBOARD_2_EXPORT_VALID: True"
)

=== Dashboard 2: Comparative Model Performance ===

=== Dashboard 2 Export Audit ===

,File,Rows,Columns,Missing Cells,Size (bytes)
0,tableau_d2_model_performance.csv,5,13,0,956
1,tableau_d2_metrics_long.csv,35,4,0,2072
2,tableau_d2_confusion_matrix.csv,20,5,0,991

=== Frozen Imbalance-Aware Model Performance ===

,Model,Configuration,Accuracy,Churn Precision,Churn Recall,Churn F1,ROC-AUC,PR-AUC,CV PR-AUC,TN,FP,FN,TP
0,Logistic Regression,Imbalance-Aware,0.645772,0.086294,0.463636,0.145506,0.588103,0.081792,0.085750,1041,540,59,51
1,Decision Tree,Imbalance-Aware,0.649911,0.072695,0.372727,0.121662,0.518840,0.076944,0.069726,1058,523,69,41
2,Random Forest,Imbalance-Aware,0.586635,0.078684,0.500000,0.135970,0.591202,0.101223,0.092939,937,644,55,55
3,XGBoost,Imbalance-Aware,0.564755,0.077027,0.518182,0.134118,0.575838,0.085447,0.078534,898,683,53,57
4,LightGBM,Imbalance-Aware,0.583678,0.087500,0.572727,0.151807,0.576209,0.083449,0.082526,924,657,47,63

=== Long-Form Metrics Preview ===

                  Model           Metric     Value          Metric Group
0   Logistic Regression         Accuracy  0.645772               Context
1         Decision Tree         Accuracy  0.649911               Context
2         Random Forest         Accuracy  0.586635               Context
3               XGBoost         Accuracy  0.564755               Context
4              LightGBM         Accuracy  0.583678               Context
5   Logistic Regression  Churn Precision  0.086294  Churn Classification
6         Decision Tree  Churn Precision  0.072695  Churn Classification
7         Random Forest  Churn Precision  0.078684  Churn Classification
8               XGBoost  Churn Precision  0.077027  Churn Classification
9              LightGBM  Churn Precision  0.087500  Churn Classification
10  Logistic Regression     Churn Recall  0.463636  Churn Classification
11        Decision Tree     Churn Recall  0.372727  Churn Classification
12        Random Forest     Churn Recall  0.500000  Churn Classification
13              XGBoost     Churn Recall  0.518182  Churn Classification
14             LightGBM     Churn Recall  0.572727  Churn Classification

=== Confusion Matrix Dataset ===

                  Model Actual Class Predicted Class         Outcome  Count
0   Logistic Regression    Non-Churn       Non-Churn   True Negative   1041
1   Logistic Regression    Non-Churn           Churn  False Positive    540
2   Logistic Regression        Churn       Non-Churn  False Negative     59
3   Logistic Regression        Churn           Churn   True Positive     51
4         Decision Tree    Non-Churn       Non-Churn   True Negative   1058
5         Decision Tree    Non-Churn           Churn  False Positive    523
6         Decision Tree        Churn       Non-Churn  False Negative     69
7         Decision Tree        Churn           Churn   True Positive     41
8         Random Forest    Non-Churn       Non-Churn   True Negative    937
9         Random Forest    Non-Churn           Churn  False Positive    644
10        Random Forest        Churn       Non-Churn  False Negative     55
11        Random Forest        Churn           Churn   True Positive     55
12              XGBoost    Non-Churn       Non-Churn   True Negative    898
13              XGBoost    Non-Churn           Churn  False Positive    683
14              XGBoost        Churn       Non-Churn  False Negative     53
15              XGBoost        Churn           Churn   True Positive     57
16             LightGBM    Non-Churn       Non-Churn   True Negative    924
17             LightGBM    Non-Churn           Churn  False Positive    657
18             LightGBM        Churn       Non-Churn  False Negative     47
19             LightGBM        Churn           Churn   True Positive     63

TABLEAU_DASHBOARD_2_EXPORT_VALID: True

### Dashboard 2 Export Interpretation

Three Tableau-ready datasets were generated to support the **Comparative Model Performance** dashboard. The exported results correspond exclusively to the five frozen imbalance-aware model configurations evaluated on the held-out test set. No models were retrained, retuned or otherwise modified during Tableau preparation.

The comparison demonstrates that no single model dominates every predictive metric. **LightGBM achieved the highest churn precision (0.0875), churn recall (0.5727) and churn F1-score (0.1518)**, whereas **Random Forest achieved the highest ROC-AUC (0.5912) and PR-AUC (0.1012)**. Logistic Regression retained competitive churn F1 and ROC-AUC performance while providing substantially greater intrinsic transparency than the ensemble models.

Accuracy is retained within the Tableau dataset for descriptive completeness but is treated as a contextual measure because only approximately 6.49% of customers belong to the churn class. Greater emphasis is therefore placed on churn-class precision, recall and F1-score together with ROC-AUC and PR-AUC.

The confusion-matrix export preserves the same held-out test population for every model: **1,691 observations comprising 110 churn and 1,581 non-churn cases**. This enables the dashboard to communicate the trade-off between detecting additional churners and generating additional false-positive churn classifications.

These visualisations present the previously established predictive evidence and do not introduce a new composite performance score or an additional model-ranking procedure.

In [ ]:
# ============================================================
# Cell 8 — Tableau Dashboard 3 Exports
# Explainability and Final Model Selection
# ============================================================

import os
import pandas as pd


print(
    "=== Dashboard 3: Explainability and Final Model Selection ===\n"
)


# ------------------------------------------------------------
# Load authoritative Notebook 3 artefacts
# ------------------------------------------------------------

explainability_ranks = pd.read_csv(
    os.path.join(
        OUTPUTS,
        "cross_model_explainability_ranks.csv"
    )
)

perturbation = pd.read_csv(
    os.path.join(
        OUTPUTS,
        "cross_model_perturbation_sensitivity.csv"
    )
)

explainability_summary = pd.read_csv(
    os.path.join(
        OUTPUTS,
        "cross_model_explainability_summary.csv"
    )
)

final_assessment = pd.read_csv(
    os.path.join(
        OUTPUTS,
        "final_performance_interpretability_assessment.csv"
    )
)

selection_evidence = pd.read_csv(
    os.path.join(
        OUTPUTS,
        "final_model_selection_evidence.csv"
    )
)


# ------------------------------------------------------------
# 1. Cross-model explainability ranks — long format
#
# Ranks are used for cross-model comparison rather than
# comparing raw SHAP magnitudes across different explainers.
# ------------------------------------------------------------

rank_columns = {
    "Decision Tree Rank": "Decision Tree",
    "Random Forest Rank": "Random Forest",
    "XGBoost Rank": "XGBoost",
    "LightGBM Rank": "LightGBM"
}


d3_explainability_ranks_long = (
    explainability_ranks[
        ["Feature"] + list(rank_columns.keys())
    ]
    .melt(
        id_vars="Feature",
        var_name="Rank Source",
        value_name="Feature Rank"
    )
)


d3_explainability_ranks_long[
    "Model"
] = (
    d3_explainability_ranks_long[
        "Rank Source"
    ]
    .map(rank_columns)
)


d3_explainability_ranks_long = (
    d3_explainability_ranks_long[
        [
            "Model",
            "Feature",
            "Feature Rank"
        ]
    ]
    .sort_values(
        [
            "Model",
            "Feature Rank",
            "Feature"
        ]
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# Add descriptive mean rank
#
# This is retained only as a summary of rank consistency.
# It is NOT a performance–interpretability composite score.
# ------------------------------------------------------------

mean_rank_lookup = (
    explainability_ranks[
        [
            "Feature",
            "Mean Rank"
        ]
    ]
    .copy()
)


d3_explainability_ranks_long = (
    d3_explainability_ranks_long
    .merge(
        mean_rank_lookup,
        on="Feature",
        how="left"
    )
)


# ------------------------------------------------------------
# 2. Perturbation sensitivity
#
# Keep original Notebook 3 quantities unchanged.
# ------------------------------------------------------------

d3_perturbation = (
    perturbation
    .copy()
)


# Add a note-friendly direction field for metric changes.
# No new score is calculated.

d3_perturbation[
    "ROC-AUC Change Direction"
] = d3_perturbation[
    "ROC-AUC Change"
].apply(
    lambda x:
        "Decreased"
        if x < 0
        else (
            "Increased"
            if x > 0
            else "No Change"
        )
)


d3_perturbation[
    "PR-AUC Change Direction"
] = d3_perturbation[
    "PR-AUC Change"
].apply(
    lambda x:
        "Decreased"
        if x < 0
        else (
            "Increased"
            if x > 0
            else "No Change"
        )
)


# ------------------------------------------------------------
# 3. Explainability-method comparison
# ------------------------------------------------------------

d3_explainability_methods = (
    explainability_summary
    .copy()
)


# ------------------------------------------------------------
# 4. Final performance–interpretability assessment
# ------------------------------------------------------------

d3_final_assessment = (
    final_assessment
    .copy()
)


# Explicitly mark the model selected in Notebook 3.
# This records the established conclusion; it does not
# perform a new ranking or selection.

d3_final_assessment[
    "Final Selected Model"
] = (
    d3_final_assessment[
        "Model"
    ] == "LightGBM"
)


# ------------------------------------------------------------
# 5. Final selection evidence
# ------------------------------------------------------------

d3_selection_evidence = (
    selection_evidence
    .copy()
)


# ------------------------------------------------------------
# Validation of core dissertation evidence
# ------------------------------------------------------------

expected_models = {
    "Logistic Regression",
    "Decision Tree",
    "Random Forest",
    "XGBoost",
    "LightGBM"
}


assert set(
    d3_final_assessment["Model"]
) == expected_models


assert (
    d3_final_assessment[
        "Final Selected Model"
    ].sum()
    == 1
)


selected_model = (
    d3_final_assessment.loc[
        d3_final_assessment[
            "Final Selected Model"
        ],
        "Model"
    ]
    .iloc[0]
)


assert selected_model == "LightGBM"


# Four nonlinear models × 24 encoded inputs
assert len(
    d3_explainability_ranks_long
) == 96


# Five models × five perturbed numerical features
assert len(
    d3_perturbation
) == 25


# All five models should identify Average Mobile Revenue
# as perturbation rank 1.

rank_one_perturbation = (
    d3_perturbation[
        d3_perturbation[
            "Sensitivity Rank"
        ] == 1
    ]
)


assert len(
    rank_one_perturbation
) == 5


assert set(
    rank_one_perturbation[
        "Feature"
    ]
) == {
    "Average Mobile Revenue"
}


# Confirm the shared nonlinear top-five feature set
top_five = (
    d3_explainability_ranks_long[
        d3_explainability_ranks_long[
            "Feature Rank"
        ] <= 5
    ]
)


expected_top_five = {
    "Average Mobile Revenue",
    "ARPU",
    "Active Subscribers",
    "Inactive Subscriber Ratio",
    "Inactive Subscribers"
}


for model in [
    "Decision Tree",
    "Random Forest",
    "XGBoost",
    "LightGBM"
]:

    model_top_five = set(
        top_five.loc[
            top_five["Model"] == model,
            "Feature"
        ]
    )

    assert model_top_five == expected_top_five


# ------------------------------------------------------------
# Export
# ------------------------------------------------------------

d3_files = {

    "tableau_d3_explainability_ranks.csv":
        d3_explainability_ranks_long,

    "tableau_d3_perturbation_sensitivity.csv":
        d3_perturbation,

    "tableau_d3_explainability_methods.csv":
        d3_explainability_methods,

    "tableau_d3_final_assessment.csv":
        d3_final_assessment,

    "tableau_d3_selection_evidence.csv":
        d3_selection_evidence
}


for filename, df in d3_files.items():

    filepath = os.path.join(
        TABLEAU,
        filename
    )

    df.to_csv(
        filepath,
        index=False
    )


# ------------------------------------------------------------
# Export audit
# ------------------------------------------------------------

audit_rows = []


for filename, df in d3_files.items():

    filepath = os.path.join(
        TABLEAU,
        filename
    )

    audit_rows.append({

        "File":
            filename,

        "Rows":
            len(df),

        "Columns":
            len(df.columns),

        "Missing Cells":
            int(
                df.isna()
                .sum()
                .sum()
            ),

        "Size (bytes)":
            os.path.getsize(
                filepath
            )
    })


d3_export_audit = pd.DataFrame(
    audit_rows
)


print(
    "=== Dashboard 3 Export Audit ===\n"
)

display(
    d3_export_audit
)


print(
    "\n=== Cross-Model Top Five Explainability Features ===\n"
)

display(
    d3_explainability_ranks_long[
        d3_explainability_ranks_long[
            "Feature Rank"
        ] <= 5
    ]
)


print(
    "\n=== Perturbation Rank-1 Feature by Model ===\n"
)

display(
    rank_one_perturbation[
        [
            "Model",
            "Feature",
            "Mean Absolute Probability Change",
            "ROC-AUC Change",
            "PR-AUC Change"
        ]
    ]
)


print(
    "\n=== Explainability Methods ===\n"
)

display(
    d3_explainability_methods
)


print(
    "\n=== Final Performance–Interpretability Assessment ===\n"
)

display(
    d3_final_assessment
)


print(
    "\n=== Final Selection Evidence ===\n"
)

display(
    d3_selection_evidence
)


# ------------------------------------------------------------
# Final validation
# ------------------------------------------------------------

assert all(
    os.path.exists(
        os.path.join(
            TABLEAU,
            filename
        )
    )
    for filename
    in d3_files
)


assert (
    d3_export_audit[
        "Missing Cells"
    ].sum()
    == 0
)


print(
    "\nFinal selected model:",
    selected_model
)


print(
    "\nTABLEAU_DASHBOARD_3_EXPORT_VALID: True"
)

=== Dashboard 3: Explainability and Final Model Selection ===

=== Dashboard 3 Export Audit ===

,File,Rows,Columns,Missing Cells,Size (bytes)
0,tableau_d3_explainability_ranks.csv,96,4,0,4365
1,tableau_d3_perturbation_sensitivity.csv,25,10,0,3747
2,tableau_d3_explainability_methods.csv,5,6,0,701
3,tableau_d3_final_assessment.csv,5,14,0,1107
4,tableau_d3_selection_evidence.csv,10,3,0,1408

=== Cross-Model Top Five Explainability Features ===

            Model                    Feature  Feature Rank  Mean Rank
0   Decision Tree     Average Mobile Revenue           1.0       1.00
1   Decision Tree         Active Subscribers           2.0       2.75
2   Decision Tree                       ARPU           3.0       2.25
3   Decision Tree       Inactive Subscribers           4.0       4.75
4   Decision Tree  Inactive Subscriber Ratio           5.0       4.25
24       LightGBM     Average Mobile Revenue           1.0       1.00
25       LightGBM                       ARPU           2.0       2.25
26       LightGBM         Active Subscribers           3.0       2.75
27       LightGBM  Inactive Subscriber Ratio           4.0       4.25
28       LightGBM       Inactive Subscribers           5.0       4.75
48  Random Forest     Average Mobile Revenue           1.0       1.00
49  Random Forest                       ARPU           2.0       2.25
50  Random Forest         Active Subscribers           3.0       2.75
51  Random Forest  Inactive Subscriber Ratio           4.0       4.25
52  Random Forest       Inactive Subscribers           5.0       4.75
72        XGBoost     Average Mobile Revenue           1.0       1.00
73        XGBoost                       ARPU           2.0       2.25
74        XGBoost         Active Subscribers           3.0       2.75
75        XGBoost  Inactive Subscriber Ratio           4.0       4.25
76        XGBoost       Inactive Subscribers           5.0       4.75

=== Perturbation Rank-1 Feature by Model ===

,Model,Feature,Mean Absolute Probability Change,ROC-AUC Change,PR-AUC Change
0,Decision Tree,Average Mobile Revenue,0.264109,-0.029323,-0.018294
5,LightGBM,Average Mobile Revenue,0.092403,-0.092335,-0.019019
10,Logistic Regression,Average Mobile Revenue,0.011432,-0.109692,-0.021017
15,Random Forest,Average Mobile Revenue,0.055874,-0.080435,-0.020741
20,XGBoost,Average Mobile Revenue,0.082141,-0.060413,-0.006930

=== Explainability Methods ===

,Model,Primary Explanation Method,Intrinsic / Post-hoc,Observed Model Complexity,Most Influential Feature,Explainability Scope Demonstrated
0,Logistic Regression,Intrinsic coefficients,Intrinsic,1 non-zero coefficient from 24 inputs,Average Mobile Revenue,Global intrinsic
1,Decision Tree,Intrinsic rules + permutation SHAP,Intrinsic + post-hoc,Depth 10; 405 nodes,Average Mobile Revenue,Global intrinsic + global SHAP
2,Random Forest,Permutation SHAP,Post-hoc,50-tree ensemble,Average Mobile Revenue,Global SHAP
3,XGBoost,Native TreeSHAP,Post-hoc,50-tree boosted ensemble,Average Mobile Revenue,Global SHAP
4,LightGBM,Native TreeSHAP,Post-hoc,50-tree boosted ensemble,Average Mobile Revenue,Global + local SHAP

=== Final Performance–Interpretability Assessment ===

,Model,Accuracy,Churn Precision,Churn Recall,Churn F1,ROC-AUC,PR-AUC,Interpretability Basis,Intrinsic Transparency,Fitted Model Complexity,Explanation Scope,Leading Explained Feature,Perturbation Rank-1 Feature,Final Selected Model
0,Logistic Regression,0.6458,0.0863,0.4636,0.1455,0.5881,0.0818,Intrinsic coefficients,High,Sparse: 1/24 non-zero coefficients,Global intrinsic,Average Mobile Revenue,Average Mobile Revenue,False
1,Decision Tree,0.6499,0.0727,0.3727,0.1217,0.5188,0.0769,Intrinsic rules + permutation SHAP,Moderate,Depth 10; 405 nodes,Global intrinsic + global SHAP,Average Mobile Revenue,Average Mobile Revenue,False
2,Random Forest,0.5866,0.0787,0.5000,0.1360,0.5912,0.1012,Permutation SHAP,Low,50-tree ensemble,Global SHAP,Average Mobile Revenue,Average Mobile Revenue,False
3,XGBoost,0.5648,0.0770,0.5182,0.1341,0.5758,0.0854,Native TreeSHAP,Low,50-tree boosted ensemble,Global SHAP,Average Mobile Revenue,Average Mobile Revenue,False
4,LightGBM,0.5837,0.0875,0.5727,0.1518,0.5762,0.0834,Native TreeSHAP,Low,50-tree boosted ensemble,Global + local SHAP,Average Mobile Revenue,Average Mobile Revenue,True

=== Final Selection Evidence ===

,Assessment Dimension,Evidence,Implication
0,Churn Precision,LightGBM highest: 0.0875,Strongest threshold-based precision for identi...
1,Churn Recall,LightGBM highest: 0.5727,Recovered the largest proportion of actual chu...
2,Churn F1,LightGBM highest: 0.1518,Best observed balance of churn precision and r...
3,ROC-AUC,Random Forest highest: 0.5912; LightGBM: 0.5762,LightGBM did not lead this discrimination measure
4,PR-AUC,Random Forest highest: 0.1012; LightGBM: 0.0834,LightGBM did not lead this imbalance-sensitive...
5,Intrinsic Transparency,Logistic Regression strongest intrinsically; L...,Selection requires accepting lower intrinsic t...
6,Global Explainability,LightGBM supported efficient native TreeSHAP g...,Model complexity can be examined through effic...
7,Local Explainability,LightGBM demonstrated individual-level TreeSHA...,Individual predictions can be investigated in ...
8,Perturbation Consistency,LightGBM perturbation ordering broadly reinfor...,Independent sensitivity analysis provides comp...
9,Overall Performance–Interpretability Balance,LightGBM selected,Strongest overall balance under the evidence a...

Final selected model: LightGBM

TABLEAU_DASHBOARD_3_EXPORT_VALID: True

### Dashboard 3 Export Interpretation

Five Tableau-ready datasets were generated for the **Explainability and Final Model Selection** dashboard, using previously established results without recomputing SHAP values or performing additional model selection.

Decision Tree, Random Forest, XGBoost and LightGBM identified the same five leading features, with **Average Mobile Revenue** ranked first in each model. Feature ranks were used for cross-model comparisons because explanation methods, output scales and sample sizes differed.

Perturbation results provided complementary evidence, with **Average Mobile Revenue** the most prediction-sensitive feature across all five models. These findings indicate predictive dependence rather than causal relationships.

**LightGBM remained the selected model** because of its leading churn precision, recall and F1-score and its support for efficient global and local TreeSHAP explanations. This selection acknowledges Random Forest's stronger ROC-AUC and PR-AUC and Logistic Regression's greater intrinsic transparency.

In [ ]:
# ============================================================
# Cell 9 — Master Tableau Export Audit
# ============================================================

import os
import pandas as pd


print("=== MASTER TABLEAU EXPORT AUDIT ===\n")


# ------------------------------------------------------------
# Expected Tableau exports
# ------------------------------------------------------------

expected_exports = {

    # Dashboard 1
    "tableau_d1_dataset_summary.csv": (1, 8),
    "tableau_d1_churn_distribution.csv": (2, 3),
    "tableau_d1_crm_segment_churn.csv": (16, 4),
    "tableau_d1_effective_segment_churn.csv": (11, 4),
    "tableau_d1_numeric_profile.csv": (14, 8),

    # Dashboard 2
    "tableau_d2_model_performance.csv": (5, 13),
    "tableau_d2_metrics_long.csv": (35, 4),
    "tableau_d2_confusion_matrix.csv": (20, 5),

    # Dashboard 3
    "tableau_d3_explainability_ranks.csv": (96, 4),
    "tableau_d3_perturbation_sensitivity.csv": (25, 10),
    "tableau_d3_explainability_methods.csv": (5, 6),
    "tableau_d3_final_assessment.csv": (5, 14),
    "tableau_d3_selection_evidence.csv": (10, 3)
}


# ------------------------------------------------------------
# Load and audit every expected export
# ------------------------------------------------------------

loaded_exports = {}
audit_rows = []


for filename, expected_shape in expected_exports.items():

    filepath = os.path.join(
        TABLEAU,
        filename
    )

    exists = os.path.exists(
        filepath
    )

    assert exists, (
        f"Missing Tableau export: {filename}"
    )

    df = pd.read_csv(
        filepath
    )

    loaded_exports[
        filename
    ] = df

    actual_shape = df.shape

    shape_valid = (
        actual_shape
        == expected_shape
    )

    missing_cells = int(
        df.isna()
        .sum()
        .sum()
    )

    duplicate_rows = int(
        df.duplicated()
        .sum()
    )

    audit_rows.append({

        "Dashboard":
            filename.split("_")[2].upper(),

        "File":
            filename,

        "Rows":
            actual_shape[0],

        "Columns":
            actual_shape[1],

        "Expected Rows":
            expected_shape[0],

        "Expected Columns":
            expected_shape[1],

        "Shape Valid":
            shape_valid,

        "Missing Cells":
            missing_cells,

        "Duplicate Rows":
            duplicate_rows,

        "Size (bytes)":
            os.path.getsize(
                filepath
            )
    })


master_audit = pd.DataFrame(
    audit_rows
)


# ------------------------------------------------------------
# Dashboard 1 integrity checks
# ------------------------------------------------------------

d1_summary_check = loaded_exports[
    "tableau_d1_dataset_summary.csv"
]

d1_churn_check = loaded_exports[
    "tableau_d1_churn_distribution.csv"
]

d1_crm_check = loaded_exports[
    "tableau_d1_crm_segment_churn.csv"
]

d1_effective_check = loaded_exports[
    "tableau_d1_effective_segment_churn.csv"
]


assert int(
    d1_summary_check.loc[
        0,
        "Total Customers"
    ]
) == 8453


assert int(
    d1_summary_check.loc[
        0,
        "Churn Customers"
    ]
) == 549


assert int(
    d1_summary_check.loc[
        0,
        "Non-Churn Customers"
    ]
) == 7904


assert (
    d1_churn_check[
        "Customer Count"
    ].sum()
    == 8453
)


assert (
    d1_crm_check[
        "Customer Count"
    ].sum()
    == 8453
)


assert (
    d1_effective_check[
        "Customer Count"
    ].sum()
    == 8453
)


# ------------------------------------------------------------
# Dashboard 2 integrity checks
# ------------------------------------------------------------

d2_performance_check = loaded_exports[
    "tableau_d2_model_performance.csv"
]

d2_metrics_check = loaded_exports[
    "tableau_d2_metrics_long.csv"
]

d2_cm_check = loaded_exports[
    "tableau_d2_confusion_matrix.csv"
]


expected_models = {
    "Logistic Regression",
    "Decision Tree",
    "Random Forest",
    "XGBoost",
    "LightGBM"
}


assert set(
    d2_performance_check[
        "Model"
    ]
) == expected_models


assert set(
    d2_metrics_check[
        "Model"
    ]
) == expected_models


assert set(
    d2_cm_check[
        "Model"
    ]
) == expected_models


for model in expected_models:

    model_cm = d2_cm_check[
        d2_cm_check[
            "Model"
        ] == model
    ]

    assert (
        model_cm[
            "Count"
        ].sum()
        == 1691
    )

    assert (
        model_cm.loc[
            model_cm[
                "Actual Class"
            ] == "Churn",
            "Count"
        ].sum()
        == 110
    )

    assert (
        model_cm.loc[
            model_cm[
                "Actual Class"
            ] == "Non-Churn",
            "Count"
        ].sum()
        == 1581
    )


# ------------------------------------------------------------
# Dashboard 3 integrity checks
# ------------------------------------------------------------

d3_ranks_check = loaded_exports[
    "tableau_d3_explainability_ranks.csv"
]

d3_perturbation_check = loaded_exports[
    "tableau_d3_perturbation_sensitivity.csv"
]

d3_methods_check = loaded_exports[
    "tableau_d3_explainability_methods.csv"
]

d3_assessment_check = loaded_exports[
    "tableau_d3_final_assessment.csv"
]


# Four nonlinear models represented in SHAP rank comparison
expected_explained_models = {
    "Decision Tree",
    "Random Forest",
    "XGBoost",
    "LightGBM"
}


assert set(
    d3_ranks_check[
        "Model"
    ]
) == expected_explained_models


# All five models represented in perturbation analysis
assert set(
    d3_perturbation_check[
        "Model"
    ]
) == expected_models


assert set(
    d3_methods_check[
        "Model"
    ]
) == expected_models


assert set(
    d3_assessment_check[
        "Model"
    ]
) == expected_models


# Exactly one final selected model
selected_rows = (
    d3_assessment_check[
        d3_assessment_check[
            "Final Selected Model"
        ] == True
    ]
)


assert len(
    selected_rows
) == 1


assert (
    selected_rows[
        "Model"
    ].iloc[0]
    == "LightGBM"
)


# Average Mobile Revenue must be perturbation rank 1
# for all five models.

perturbation_rank_one = (
    d3_perturbation_check[
        d3_perturbation_check[
            "Sensitivity Rank"
        ] == 1
    ]
)


assert len(
    perturbation_rank_one
) == 5


assert set(
    perturbation_rank_one[
        "Feature"
    ]
) == {
    "Average Mobile Revenue"
}


# ------------------------------------------------------------
# Global export-quality checks
# ------------------------------------------------------------

assert master_audit[
    "Shape Valid"
].all()


assert (
    master_audit[
        "Missing Cells"
    ].sum()
    == 0
)


assert (
    master_audit[
        "Duplicate Rows"
    ].sum()
    == 0
)


# ------------------------------------------------------------
# Save audit itself
# ------------------------------------------------------------

audit_output_path = os.path.join(
    TABLEAU,
    "tableau_master_export_audit.csv"
)


master_audit.to_csv(
    audit_output_path,
    index=False
)


# ------------------------------------------------------------
# Display audit
# ------------------------------------------------------------

print(
    "=== Export File Audit ===\n"
)

display(
    master_audit
)


print(
    "\n=== Dashboard Summary ===\n"
)


dashboard_summary = (
    master_audit
    .groupby(
        "Dashboard"
    )
    .agg(
        Files=("File", "count"),
        Total_Rows=("Rows", "sum"),
        Missing_Cells=("Missing Cells", "sum"),
        Duplicate_Rows=("Duplicate Rows", "sum")
    )
    .reset_index()
)


display(
    dashboard_summary
)


# ------------------------------------------------------------
# Directory inventory
# ------------------------------------------------------------

print(
    "\n=== Final Tableau Directory Inventory ===\n"
)


tableau_inventory = []


for filename in sorted(
    os.listdir(TABLEAU)
):

    filepath = os.path.join(
        TABLEAU,
        filename
    )

    if os.path.isfile(
        filepath
    ):

        tableau_inventory.append({

            "File":
                filename,

            "Size (bytes)":
                os.path.getsize(
                    filepath
                )
        })


tableau_inventory = pd.DataFrame(
    tableau_inventory
)


display(
    tableau_inventory
)


# ------------------------------------------------------------
# Final report
# ------------------------------------------------------------

print(
    "\nExpected dashboard exports:",
    len(expected_exports)
)

print(
    "Validated dashboard exports:",
    len(master_audit)
)

print(
    "Total missing cells:",
    int(
        master_audit[
            "Missing Cells"
        ].sum()
    )
)

print(
    "Total duplicate rows:",
    int(
        master_audit[
            "Duplicate Rows"
        ].sum()
    )
)

print(
    "Final selected model:",
    selected_rows[
        "Model"
    ].iloc[0]
)

print(
    "Master audit saved:",
    audit_output_path
)


print(
    "\nTABLEAU_MASTER_EXPORT_AUDIT_VALID: True"
)

=== MASTER TABLEAU EXPORT AUDIT ===

=== Export File Audit ===

,Dashboard,File,Rows,Columns,Expected Rows,Expected Columns,Shape Valid,Missing Cells,Duplicate Rows,Size (bytes)
0,DATASET,tableau_d1_dataset_summary.csv,1,8,1,8,True,0,0,196
1,CHURN,tableau_d1_churn_distribution.csv,2,3,2,3,True,0,0,94
2,CRM,tableau_d1_crm_segment_churn.csv,16,4,16,4,True,0,0,556
3,EFFECTIVE,tableau_d1_effective_segment_churn.csv,11,4,11,4,True,0,0,394
4,NUMERIC,tableau_d1_numeric_profile.csv,14,8,14,8,True,0,0,1248
5,MODEL,tableau_d2_model_performance.csv,5,13,5,13,True,0,0,956
6,METRICS,tableau_d2_metrics_long.csv,35,4,35,4,True,0,0,2072
7,CONFUSION,tableau_d2_confusion_matrix.csv,20,5,20,5,True,0,0,991
8,EXPLAINABILITY,tableau_d3_explainability_ranks.csv,96,4,96,4,True,0,0,4365
9,PERTURBATION,tableau_d3_perturbation_sensitivity.csv,25,10,25,10,True,0,0,3747
10,EXPLAINABILITY,tableau_d3_explainability_methods.csv,5,6,5,6,True,0,0,701
11,FINAL,tableau_d3_final_assessment.csv,5,14,5,14,True,0,0,1107
12,SELECTION,tableau_d3_selection_evidence.csv,10,3,10,3,True,0,0,1408

=== Dashboard Summary ===

         Dashboard  Files  Total_Rows  Missing_Cells  Duplicate_Rows
0            CHURN      1           2              0               0
1        CONFUSION      1          20              0               0
2              CRM      1          16              0               0
3          DATASET      1           1              0               0
4        EFFECTIVE      1          11              0               0
5   EXPLAINABILITY      2         101              0               0
6            FINAL      1           5              0               0
7          METRICS      1          35              0               0
8            MODEL      1           5              0               0
9          NUMERIC      1          14              0               0
10    PERTURBATION      1          25              0               0
11       SELECTION      1          10              0               0

=== Final Tableau Directory Inventory ===

                                       File  Size (bytes)
0         tableau_d1_churn_distribution.csv            94
1          tableau_d1_crm_segment_churn.csv           556
2            tableau_d1_dataset_summary.csv           196
3    tableau_d1_effective_segment_churn.csv           394
4            tableau_d1_numeric_profile.csv          1248
5           tableau_d2_confusion_matrix.csv           991
6               tableau_d2_metrics_long.csv          2072
7          tableau_d2_model_performance.csv           956
8     tableau_d3_explainability_methods.csv           701
9       tableau_d3_explainability_ranks.csv          4365
10          tableau_d3_final_assessment.csv          1107
11  tableau_d3_perturbation_sensitivity.csv          3747
12        tableau_d3_selection_evidence.csv          1408
13          tableau_master_export_audit.csv           973

Expected dashboard exports: 13
Validated dashboard exports: 13
Total missing cells: 0
Total duplicate rows: 0
Final selected model: LightGBM
Master audit saved: /content/drive/MyDrive/7005SCN_Dissertation/tableau/tableau_master_export_audit.csv

TABLEAU_MASTER_EXPORT_AUDIT_VALID: True

In [ ]:
# ============================================================
# Cell 10 — Final Audit Labelling and Notebook Completion
# ============================================================

import os
import pandas as pd


print("=== FINAL TABLEAU EXPORT SUMMARY ===\n")


# ------------------------------------------------------------
# Correct dashboard labels in master audit
# ------------------------------------------------------------

def get_dashboard_label(filename):

    if filename.startswith("tableau_d1_"):
        return "Dashboard 1 — Dataset and Churn Profile"

    elif filename.startswith("tableau_d2_"):
        return "Dashboard 2 — Comparative Model Performance"

    elif filename.startswith("tableau_d3_"):
        return "Dashboard 3 — Explainability and Final Model Selection"

    else:
        return "Other"


master_audit[
    "Dashboard"
] = master_audit[
    "File"
].apply(
    get_dashboard_label
)


# ------------------------------------------------------------
# Re-save corrected master audit
# ------------------------------------------------------------

audit_output_path = os.path.join(
    TABLEAU,
    "tableau_master_export_audit.csv"
)


master_audit.to_csv(
    audit_output_path,
    index=False
)


# ------------------------------------------------------------
# Dashboard-level summary
# ------------------------------------------------------------

dashboard_summary_final = (
    master_audit
    .groupby(
        "Dashboard",
        sort=False
    )
    .agg(
        Export_Files=("File", "count"),
        Total_Rows=("Rows", "sum"),
        Missing_Cells=("Missing Cells", "sum"),
        Duplicate_Rows=("Duplicate Rows", "sum")
    )
    .reset_index()
)


print(
    "=== Dashboard-Level Export Summary ===\n"
)

display(
    dashboard_summary_final
)


# ------------------------------------------------------------
# Final file inventory
# ------------------------------------------------------------

final_inventory = []


for filename in sorted(
    os.listdir(TABLEAU)
):

    filepath = os.path.join(
        TABLEAU,
        filename
    )

    if os.path.isfile(
        filepath
    ):

        final_inventory.append({

            "File":
                filename,

            "Size (bytes)":
                os.path.getsize(
                    filepath
                )
        })


final_inventory = pd.DataFrame(
    final_inventory
)


print(
    "\n=== Final Tableau Directory ===\n"
)

display(
    final_inventory
)


# ------------------------------------------------------------
# Final notebook validation
# ------------------------------------------------------------

assert len(
    master_audit
) == 13


assert (
    master_audit[
        "Shape Valid"
    ].all()
)


assert (
    master_audit[
        "Missing Cells"
    ].sum()
    == 0
)


assert (
    master_audit[
        "Duplicate Rows"
    ].sum()
    == 0
)


assert set(
    master_audit[
        "Dashboard"
    ]
) == {

    "Dashboard 1 — Dataset and Churn Profile",

    "Dashboard 2 — Comparative Model Performance",

    "Dashboard 3 — Explainability and Final Model Selection"
}


assert (
    dashboard_summary_final[
        "Export_Files"
    ].tolist()
    == [5, 3, 5]
)


print(
    "\nDashboard 1 exports: 5"
)

print(
    "Dashboard 2 exports: 3"
)

print(
    "Dashboard 3 exports: 5"
)

print(
    "Total analytical dashboard exports: 13"
)

print(
    "Master audit file: 1"
)

print(
    "Final selected model: LightGBM"
)

print(
    "Models retrained in Notebook 4: 0"
)

print(
    "SHAP explanations recomputed in Notebook 4: 0"
)

print(
    "New model-selection procedures in Notebook 4: 0"
)


print(
    "\nNOTEBOOK_4_COMPLETE: True"
)

=== FINAL TABLEAU EXPORT SUMMARY ===

=== Dashboard-Level Export Summary ===

,Dashboard,Export_Files,Total_Rows,Missing_Cells,Duplicate_Rows
0,Dashboard 1 — Dataset and Churn Profile,5,44,0,0
1,Dashboard 2 — Comparative Model Performance,3,60,0,0
2,Dashboard 3 — Explainability and Final Model S...,5,141,0,0

=== Final Tableau Directory ===

                                       File  Size (bytes)
0         tableau_d1_churn_distribution.csv            94
1          tableau_d1_crm_segment_churn.csv           556
2            tableau_d1_dataset_summary.csv           196
3    tableau_d1_effective_segment_churn.csv           394
4            tableau_d1_numeric_profile.csv          1248
5           tableau_d2_confusion_matrix.csv           991
6               tableau_d2_metrics_long.csv          2072
7          tableau_d2_model_performance.csv           956
8     tableau_d3_explainability_methods.csv           701
9       tableau_d3_explainability_ranks.csv          4365
10          tableau_d3_final_assessment.csv          1107
11  tableau_d3_perturbation_sensitivity.csv          3747
12        tableau_d3_selection_evidence.csv          1408
13          tableau_master_export_audit.csv          1487

Dashboard 1 exports: 5
Dashboard 2 exports: 3
Dashboard 3 exports: 5
Total analytical dashboard exports: 13
Master audit file: 1
Final selected model: LightGBM
Models retrained in Notebook 4: 0
SHAP explanations recomputed in Notebook 4: 0
New model-selection procedures in Notebook 4: 0

NOTEBOOK_4_COMPLETE: True

## Notebook 4 Conclusion

This notebook prepared **13 Tableau-ready analytical datasets** across three dashboards: Dataset and Churn Profile (five exports), Comparative Model Performance (three exports), and Explainability and Final Model Selection (five exports).

The master audit confirmed that all expected exports were present, with no missing values or duplicate rows in the exported datasets. No models were retrained, SHAP explanations recomputed or new model-selection procedures introduced.

The exports therefore provide a consistent visual communication layer over the results established in Notebooks 1–3, preserving **LightGBM as the final selected model**.